/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.uniovi.dsl.scheduling.ui.internal.SchedulingActivator;

public class SchedulingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SchedulingActivator.getInstance().getInjector("org.uniovi.dsl.scheduling.Scheduling");
	}

}
