/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.uniovi.dsl.scheduling.ui.syntaxhighlighting.SchedulingAntlrMapper;
import org.uniovi.dsl.scheduling.ui.syntaxhighlighting.SchedulingHighlightingCalculator;
import org.uniovi.dsl.scheduling.ui.syntaxhighlighting.SchedulingHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SchedulingUiModule extends AbstractSchedulingUiModule {

	public SchedulingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
        return SchedulingHighlightingConfiguration.class;
    }
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        return SchedulingHighlightingCalculator.class;
    }
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
        return SchedulingAntlrMapper.class;
    }
	
}
