/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SchedulingWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSchedulingWebModule extends DefaultWebModule {

}
