/*
 * generated by Xtext 2.31.0
 */
grammar InternalScheduling;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.uniovi.dsl.scheduling.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.uniovi.dsl.scheduling.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

}

@parser::members {

 	private SchedulingGrammarAccess grammarAccess;

    public InternalSchedulingParser(TokenStream input, SchedulingGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Program";
   	}

   	@Override
   	protected SchedulingGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleProgram
entryRuleProgram returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getProgramRule()); }
	iv_ruleProgram=ruleProgram
	{ $current=$iv_ruleProgram.current; }
	EOF;

// Rule Program
ruleProgram returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{ 
			  getUnorderedGroupHelper().enter(grammarAccess.getProgramAccess().getUnorderedGroup());
			}
			(
				(
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 0);
				}
							({true}?=>((
								{
									newCompositeNode(grammarAccess.getProgramAccess().getInstallationsInstallationsParserRuleCall_0_0());
								}
								lv_installations_1_0=ruleInstallations
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getProgramRule());
									}
									set(
										$current,
										"installations",
										lv_installations_1_0,
										"org.uniovi.dsl.scheduling.Scheduling.Installations");
									afterParserOrEnumRuleCall();
								}
							)
							))
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getProgramAccess().getUnorderedGroup());
				}
			)
		)|
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 1);
				}
							({true}?=>((
								{
									newCompositeNode(grammarAccess.getProgramAccess().getMaintenancesMaintenancesParserRuleCall_1_0());
								}
								lv_maintenances_2_0=ruleMaintenances
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getProgramRule());
									}
									set(
										$current,
										"maintenances",
										lv_maintenances_2_0,
										"org.uniovi.dsl.scheduling.Scheduling.Maintenances");
									afterParserOrEnumRuleCall();
								}
							)
							))
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getProgramAccess().getUnorderedGroup());
				}
			)
		)|
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 2)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 2);
				}
							({true}?=>((
								{
									newCompositeNode(grammarAccess.getProgramAccess().getOptionsConfigParserRuleCall_2_0());
								}
								lv_options_3_0=ruleConfig
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getProgramRule());
									}
									set(
										$current,
										"options",
										lv_options_3_0,
										"org.uniovi.dsl.scheduling.Scheduling.Config");
									afterParserOrEnumRuleCall();
								}
							)
							))
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getProgramAccess().getUnorderedGroup());
				}
			)
		)
				)+
				{getUnorderedGroupHelper().canLeave(grammarAccess.getProgramAccess().getUnorderedGroup())}?
			)
		)
			{ 
			  getUnorderedGroupHelper().leave(grammarAccess.getProgramAccess().getUnorderedGroup());
			}
	)
;

// Entry rule entryRuleInstallations
entryRuleInstallations returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInstallationsRule()); }
	iv_ruleInstallations=ruleInstallations
	{ $current=$iv_ruleInstallations.current; }
	EOF;

// Rule Installations
ruleInstallations returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_INSTALLATIONS_HEADER_0=RULE_INSTALLATIONS_HEADER
		{
			newLeafNode(this_INSTALLATIONS_HEADER_0, grammarAccess.getInstallationsAccess().getINSTALLATIONS_HEADERTerminalRuleCall_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getInstallationsAccess().getInstallationsInstallationDefParserRuleCall_1_0());
				}
				lv_installations_1_0=ruleInstallationDef
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getInstallationsRule());
					}
					add(
						$current,
						"installations",
						lv_installations_1_0,
						"org.uniovi.dsl.scheduling.Scheduling.InstallationDef");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRuleInstallationDef
entryRuleInstallationDef returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInstallationDefRule()); }
	iv_ruleInstallationDef=ruleInstallationDef
	{ $current=$iv_ruleInstallationDef.current; }
	EOF;

// Rule InstallationDef
ruleInstallationDef returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_INSTALLATION_TYPE_0=RULE_INSTALLATION_TYPE
		{
			newLeafNode(this_INSTALLATION_TYPE_0, grammarAccess.getInstallationDefAccess().getINSTALLATION_TYPETerminalRuleCall_0());
		}
		(
			(
				lv_id_1_0=RULE_ID
				{
					newLeafNode(lv_id_1_0, grammarAccess.getInstallationDefAccess().getIdIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getInstallationDefRule());
					}
					setWithLastConsumed(
						$current,
						"id",
						lv_id_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		(
			(
				{ 
				  getUnorderedGroupHelper().enter(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
				}
				(
					(
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 0)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 0);
					}
								({true}?=>(otherlv_3='Name:'
								{
									newLeafNode(otherlv_3, grammarAccess.getInstallationDefAccess().getNameKeyword_2_0_0());
								}
								(
									(
										lv_installationName_4_0=RULE_STRING
										{
											newLeafNode(lv_installationName_4_0, grammarAccess.getInstallationDefAccess().getInstallationNameSTRINGTerminalRuleCall_2_0_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getInstallationDefRule());
											}
											setWithLastConsumed(
												$current,
												"installationName",
												lv_installationName_4_0,
												"org.eclipse.xtext.common.Terminals.STRING");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 1)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 1);
					}
								({true}?=>(otherlv_5='Capacity:'
								{
									newLeafNode(otherlv_5, grammarAccess.getInstallationDefAccess().getCapacityKeyword_2_1_0());
								}
								(
									(
										lv_capacity_6_0=RULE_INT
										{
											newLeafNode(lv_capacity_6_0, grammarAccess.getInstallationDefAccess().getCapacityINTTerminalRuleCall_2_1_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getInstallationDefRule());
											}
											setWithLastConsumed(
												$current,
												"capacity",
												lv_capacity_6_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
					}
				)
			)
					)+
					{getUnorderedGroupHelper().canLeave(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2())}?
				)
			)
				{ 
				  getUnorderedGroupHelper().leave(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
				}
		)
	)
;

// Entry rule entryRuleMaintenances
entryRuleMaintenances returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMaintenancesRule()); }
	iv_ruleMaintenances=ruleMaintenances
	{ $current=$iv_ruleMaintenances.current; }
	EOF;

// Rule Maintenances
ruleMaintenances returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_MAINTENANCES_HEADER_0=RULE_MAINTENANCES_HEADER
		{
			newLeafNode(this_MAINTENANCES_HEADER_0, grammarAccess.getMaintenancesAccess().getMAINTENANCES_HEADERTerminalRuleCall_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMaintenancesAccess().getMaintsMaintDefParserRuleCall_1_0());
				}
				lv_maints_1_0=ruleMaintDef
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMaintenancesRule());
					}
					add(
						$current,
						"maints",
						lv_maints_1_0,
						"org.uniovi.dsl.scheduling.Scheduling.MaintDef");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRuleMaintDef
entryRuleMaintDef returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMaintDefRule()); }
	iv_ruleMaintDef=ruleMaintDef
	{ $current=$iv_ruleMaintDef.current; }
	EOF;

// Rule MaintDef
ruleMaintDef returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_MAINTENANCE_TYPE_0=RULE_MAINTENANCE_TYPE
		{
			newLeafNode(this_MAINTENANCE_TYPE_0, grammarAccess.getMaintDefAccess().getMAINTENANCE_TYPETerminalRuleCall_0());
		}
		(
			(
				lv_id_1_0=RULE_ID
				{
					newLeafNode(lv_id_1_0, grammarAccess.getMaintDefAccess().getIdIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMaintDefRule());
					}
					setWithLastConsumed(
						$current,
						"id",
						lv_id_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		(
			(
				{ 
				  getUnorderedGroupHelper().enter(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
				}
				(
					(
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 0)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 0);
					}
								({true}?=>(otherlv_3='Name:'
								{
									newLeafNode(otherlv_3, grammarAccess.getMaintDefAccess().getNameKeyword_2_0_0());
								}
								(
									(
										lv_maintName_4_0=RULE_STRING
										{
											newLeafNode(lv_maintName_4_0, grammarAccess.getMaintDefAccess().getMaintNameSTRINGTerminalRuleCall_2_0_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getMaintDefRule());
											}
											setWithLastConsumed(
												$current,
												"maintName",
												lv_maintName_4_0,
												"org.eclipse.xtext.common.Terminals.STRING");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 1)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 1);
					}
								({true}?=>(otherlv_5='Interval:'
								{
									newLeafNode(otherlv_5, grammarAccess.getMaintDefAccess().getIntervalKeyword_2_1_0());
								}
								(
									(
										lv_hours_6_0=RULE_INT
										{
											newLeafNode(lv_hours_6_0, grammarAccess.getMaintDefAccess().getHoursINTTerminalRuleCall_2_1_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getMaintDefRule());
											}
											setWithLastConsumed(
												$current,
												"hours",
												lv_hours_6_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 2)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 2);
					}
								({true}?=>(otherlv_7='Periods:'
								{
									newLeafNode(otherlv_7, grammarAccess.getMaintDefAccess().getPeriodsKeyword_2_2_0());
								}
								(
									(
										lv_duration_8_0=RULE_INT
										{
											newLeafNode(lv_duration_8_0, grammarAccess.getMaintDefAccess().getDurationINTTerminalRuleCall_2_2_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getMaintDefRule());
											}
											setWithLastConsumed(
												$current,
												"duration",
												lv_duration_8_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 3)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 3);
					}
								({true}?=>(otherlv_9='Priority:'
								{
									newLeafNode(otherlv_9, grammarAccess.getMaintDefAccess().getPriorityKeyword_2_3_0());
								}
								(
									(
										lv_priority_10_0=RULE_INT
										{
											newLeafNode(lv_priority_10_0, grammarAccess.getMaintDefAccess().getPriorityINTTerminalRuleCall_2_3_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getMaintDefRule());
											}
											setWithLastConsumed(
												$current,
												"priority",
												lv_priority_10_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 4)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 4);
					}
								({true}?=>(otherlv_11='Includes:'
								{
									newLeafNode(otherlv_11, grammarAccess.getMaintDefAccess().getIncludesKeyword_2_4_0());
								}
								(
									(
										{
											newCompositeNode(grammarAccess.getMaintDefAccess().getIncludesListParserRuleCall_2_4_1_0());
										}
										lv_includes_12_0=ruleList
										{
											if ($current==null) {
												$current = createModelElementForParent(grammarAccess.getMaintDefRule());
											}
											set(
												$current,
												"includes",
												lv_includes_12_0,
												"org.uniovi.dsl.scheduling.Scheduling.List");
											afterParserOrEnumRuleCall();
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 5)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 5);
					}
								({true}?=>(otherlv_13='Installations:'
								{
									newLeafNode(otherlv_13, grammarAccess.getMaintDefAccess().getInstallationsKeyword_2_5_0());
								}
								(
									(
										{
											newCompositeNode(grammarAccess.getMaintDefAccess().getInstallationsListParserRuleCall_2_5_1_0());
										}
										lv_installations_14_0=ruleList
										{
											if ($current==null) {
												$current = createModelElementForParent(grammarAccess.getMaintDefRule());
											}
											set(
												$current,
												"installations",
												lv_installations_14_0,
												"org.uniovi.dsl.scheduling.Scheduling.List");
											afterParserOrEnumRuleCall();
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
					}
				)
			)
					)+
					{getUnorderedGroupHelper().canLeave(grammarAccess.getMaintDefAccess().getUnorderedGroup_2())}?
				)
			)
				{ 
				  getUnorderedGroupHelper().leave(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
				}
		)
	)
;

// Entry rule entryRuleConfig
entryRuleConfig returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getConfigRule()); }
	iv_ruleConfig=ruleConfig
	{ $current=$iv_ruleConfig.current; }
	EOF;

// Rule Config
ruleConfig returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_OPTIONS_HEADER_0=RULE_OPTIONS_HEADER
		{
			newLeafNode(this_OPTIONS_HEADER_0, grammarAccess.getConfigAccess().getOPTIONS_HEADERTerminalRuleCall_0());
		}
		(
			(
				{ 
				  getUnorderedGroupHelper().enter(grammarAccess.getConfigAccess().getUnorderedGroup_1());
				}
				(
					(
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 0)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 0);
					}
								({true}?=>(otherlv_2='Input:'
								{
									newLeafNode(otherlv_2, grammarAccess.getConfigAccess().getInputKeyword_1_0_0());
								}
								(
									(
										lv_input_3_0=RULE_STRING
										{
											newLeafNode(lv_input_3_0, grammarAccess.getConfigAccess().getInputSTRINGTerminalRuleCall_1_0_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"input",
												lv_input_3_0,
												"org.eclipse.xtext.common.Terminals.STRING");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 1)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 1);
					}
								({true}?=>(otherlv_4='Random_state:'
								{
									newLeafNode(otherlv_4, grammarAccess.getConfigAccess().getRandom_stateKeyword_1_1_0());
								}
								(
									(
										lv_randomState_5_0=RULE_INT
										{
											newLeafNode(lv_randomState_5_0, grammarAccess.getConfigAccess().getRandomStateINTTerminalRuleCall_1_1_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"randomState",
												lv_randomState_5_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 2)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 2);
					}
								({true}?=>(otherlv_6='Prob_before_restriction:'
								{
									newLeafNode(otherlv_6, grammarAccess.getConfigAccess().getProb_before_restrictionKeyword_1_2_0());
								}
								(
									(
										lv_probBeforeScheduling_7_0=RULE_FLOAT
										{
											newLeafNode(lv_probBeforeScheduling_7_0, grammarAccess.getConfigAccess().getProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"probBeforeScheduling",
												lv_probBeforeScheduling_7_0,
												"org.uniovi.dsl.scheduling.Scheduling.FLOAT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 3)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 3);
					}
								({true}?=>(otherlv_8='Rate_of_change:'
								{
									newLeafNode(otherlv_8, grammarAccess.getConfigAccess().getRate_of_changeKeyword_1_3_0());
								}
								(
									(
										lv_rateOfChange_9_0=RULE_FLOAT
										{
											newLeafNode(lv_rateOfChange_9_0, grammarAccess.getConfigAccess().getRateOfChangeFLOATTerminalRuleCall_1_3_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"rateOfChange",
												lv_rateOfChange_9_0,
												"org.uniovi.dsl.scheduling.Scheduling.FLOAT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 4)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 4);
					}
								({true}?=>(otherlv_10='Days_per_period:'
								{
									newLeafNode(otherlv_10, grammarAccess.getConfigAccess().getDays_per_periodKeyword_1_4_0());
								}
								(
									(
										lv_daysPerPeriod_11_0=RULE_INT
										{
											newLeafNode(lv_daysPerPeriod_11_0, grammarAccess.getConfigAccess().getDaysPerPeriodINTTerminalRuleCall_1_4_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"daysPerPeriod",
												lv_daysPerPeriod_11_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 5)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 5);
					}
								({true}?=>(otherlv_12='Number_of_periods:'
								{
									newLeafNode(otherlv_12, grammarAccess.getConfigAccess().getNumber_of_periodsKeyword_1_5_0());
								}
								(
									(
										lv_numberOfPeriods_13_0=RULE_INT
										{
											newLeafNode(lv_numberOfPeriods_13_0, grammarAccess.getConfigAccess().getNumberOfPeriodsINTTerminalRuleCall_1_5_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"numberOfPeriods",
												lv_numberOfPeriods_13_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 6)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 6);
					}
								({true}?=>(otherlv_14='Extra_hours:'
								{
									newLeafNode(otherlv_14, grammarAccess.getConfigAccess().getExtra_hoursKeyword_1_6_0());
								}
								(
									(
										lv_extraHours_15_0=RULE_INT
										{
											newLeafNode(lv_extraHours_15_0, grammarAccess.getConfigAccess().getExtraHoursINTTerminalRuleCall_1_6_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"extraHours",
												lv_extraHours_15_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)|
			(
				{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 7)}?=>(
					{
						getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 7);
					}
								({true}?=>(otherlv_16='Iterations:'
								{
									newLeafNode(otherlv_16, grammarAccess.getConfigAccess().getIterationsKeyword_1_7_0());
								}
								(
									(
										lv_maxIters_17_0=RULE_INT
										{
											newLeafNode(lv_maxIters_17_0, grammarAccess.getConfigAccess().getMaxItersINTTerminalRuleCall_1_7_1_0());
										}
										{
											if ($current==null) {
												$current = createModelElement(grammarAccess.getConfigRule());
											}
											setWithLastConsumed(
												$current,
												"maxIters",
												lv_maxIters_17_0,
												"org.eclipse.xtext.common.Terminals.INT");
										}
									)
								)
								))
					{ 
						getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
					}
				)
			)
					)+
					{getUnorderedGroupHelper().canLeave(grammarAccess.getConfigAccess().getUnorderedGroup_1())}?
				)
			)
				{ 
				  getUnorderedGroupHelper().leave(grammarAccess.getConfigAccess().getUnorderedGroup_1());
				}
		)
	)
;

// Entry rule entryRuleList
entryRuleList returns [String current=null]:
	{ newCompositeNode(grammarAccess.getListRule()); }
	iv_ruleList=ruleList
	{ $current=$iv_ruleList.current.getText(); }
	EOF;

// Rule List
ruleList returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getListAccess().getIDTerminalRuleCall_0());
		}
		(
			kw=','
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getListAccess().getCommaKeyword_1_0());
			}
			this_ID_2=RULE_ID
			{
				$current.merge(this_ID_2);
			}
			{
				newLeafNode(this_ID_2, grammarAccess.getListAccess().getIDTerminalRuleCall_1_1());
			}
		)*
	)
;

RULE_INSTALLATIONS_HEADER : '[' 'Installations' ']';

RULE_INSTALLATION_TYPE : 'Installation';

RULE_MAINTENANCES_HEADER : '[' 'Maintenances' ']';

RULE_MAINTENANCE_TYPE : 'Maintenance';

RULE_OPTIONS_HEADER : '[' 'Options' ']';

RULE_FLOAT : RULE_INT+ '.' RULE_INT+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
