/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.validation;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;
import org.uniovi.dsl.scheduling.scheduling.Config;
import org.uniovi.dsl.scheduling.scheduling.InstallationDef;
import org.uniovi.dsl.scheduling.scheduling.Installations;
import org.uniovi.dsl.scheduling.scheduling.MaintDef;
import org.uniovi.dsl.scheduling.scheduling.Maintenances;
import org.uniovi.dsl.scheduling.scheduling.Program;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SchedulingValidator extends AbstractSchedulingValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
	
	@Check
	public void checkID(InstallationDef installation) {
		Program program = (Program) installation.eContainer().eContainer();
		if (hasRepeatedId(installation.getId(), installation, program)) {
			error("Installation ID already defined", SchedulingPackage.Literals.INSTALLATION_DEF__ID);
		}
	}
	
	@Check
	public void checkID(MaintDef maint) {
		Program program = (Program) maint.eContainer().eContainer();
		if (hasRepeatedId(maint.getId(), maint, program)) {
			error("Maintenance ID already defined", SchedulingPackage.Literals.MAINT_DEF__ID);
		}
	}
	
	private boolean hasRepeatedId(String id, EObject obj, Program parent) {
		if (parent.getMaintenances() != null) {
			for (MaintDef other : parent.getMaintenances().getMaints()) {
				if (id.equals(other.getId()) && other != obj) {
					return true;
				}
			}
		}
		if (parent.getInstallations() != null) {
			for (InstallationDef other : parent.getInstallations().getInstallations()) {
				if (id.equals(other.getId()) && other != obj) {
					return true;
				}
			}
		}
		return false;
	}
	
	@Check
	public void checkMaintenanceIncludes(MaintDef maint) {
		if (maint.getIncludes() == null) return;
		
		Maintenances parent = (Maintenances) maint.eContainer();
		List<String> maints = parent.getMaints()
				.stream()
				.map(m -> m.getId())
				.collect(Collectors.toList());
		
		List<String> includes = Arrays.asList(maint.getIncludes().split("\\s*,\\s*"));
		if (!maints.containsAll(includes)) {
			error("Maintenance not defined", SchedulingPackage.Literals.MAINT_DEF__INCLUDES);
		}
	}
	
	@Check
	public void checkMaintenanceInstallations(MaintDef maint) {
		Program program = (Program) maint.eContainer().eContainer();
		Installations installations = program.getInstallations();
		if (installations == null) return;
		
		List<String> places = installations.getInstallations()
				.stream()
				.map(i -> i.getId())
				.collect(Collectors.toList());
		
		List<String> maintInstallations = Arrays.asList(maint.getInstallations().split("\\s*,\\s*"));
		if (!places.containsAll(maintInstallations)) {
			error("Installation not defined", SchedulingPackage.Literals.MAINT_DEF__INSTALLATIONS);
		}
	}
	
}
