/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.validation;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;
import org.uniovi.dsl.scheduling.scheduling.DMYDate;
import org.uniovi.dsl.scheduling.scheduling.InstallationDef;
import org.uniovi.dsl.scheduling.scheduling.Installations;
import org.uniovi.dsl.scheduling.scheduling.MaintDef;
import org.uniovi.dsl.scheduling.scheduling.Maintenances;
import org.uniovi.dsl.scheduling.scheduling.Program;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SchedulingValidator extends AbstractSchedulingValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
	
	@Check
	public void checkID(InstallationDef installation) {
		Program program = (Program) installation.eContainer().eContainer();
		if (hasRepeatedId(installation.getId(), installation, program)) {
			error("Installation ID already defined", SchedulingPackage.Literals.INSTALLATION_DEF__ID);
		}
	}
	
	@Check
	public void checkID(MaintDef maint) {
		Program program = (Program) maint.eContainer().eContainer();
		if (hasRepeatedId(maint.getId(), maint, program)) {
			error("Maintenance ID already defined", SchedulingPackage.Literals.MAINT_DEF__ID);
		}
	}
	
	private boolean hasRepeatedId(String id, EObject obj, Program parent) {
		if (parent.getMaintenances() != null) {
			for (MaintDef other : parent.getMaintenances().getMaints()) {
				if (id.equals(other.getId()) && other != obj) {
					return true;
				}
			}
		}
		if (parent.getInstallations() != null) {
			for (InstallationDef other : parent.getInstallations().getInstallations()) {
				if (id.equals(other.getId()) && other != obj) {
					return true;
				}
			}
		}
		return false;
	}
	
	@Check
	public void checkMaintenanceIncludes(MaintDef maint) {
		if (maint.getIncludes() == null) return;
		
		Maintenances parent = (Maintenances) maint.eContainer();
		List<String> maints = parent.getMaints()
				.stream()
				.map(m -> m.getId())
				.collect(Collectors.toList());
		
		List<String> includes = Arrays.asList(maint.getIncludes().split("\\s*,\\s*"));
		if (!maints.containsAll(includes)) {
			error("Maintenance not defined", SchedulingPackage.Literals.MAINT_DEF__INCLUDES);
		}
	}
	
	@Check
	public void checkMaintenanceIncludingItself(MaintDef maint) {
		if (maint.getIncludes() == null) return;
		
		List<String> includes = Arrays.asList(maint.getIncludes().split("\\s*,\\s*"));
		if (includes.contains(maint.getId())) {
			error("A maintenance can not include itself", SchedulingPackage.Literals.MAINT_DEF__INCLUDES);
		}
	}
	
	@Check
	public void checkMaintenanceInstallations(MaintDef maint) {
		Program program = (Program) maint.eContainer().eContainer();
		Installations installations = program.getInstallations();
		if (installations == null) return;
		
		List<String> places = installations.getInstallations()
				.stream()
				.map(i -> i.getId())
				.collect(Collectors.toList());
		
		List<String> maintInstallations = Arrays.asList(maint.getInstallations().split("\\s*,\\s*"));
		if (!places.containsAll(maintInstallations)) {
			error("Installation not defined", SchedulingPackage.Literals.MAINT_DEF__INSTALLATIONS);
		}
	}
	
	@Check
	public void checkDMYDate(DMYDate date) {
		String dateStr = date.getDay() + "-";
		dateStr += date.getMonth() + "-";
		dateStr += date.getYear();
		
		if (!isValidDate(date.getDay()+"-01-2000", "dd-MM-yyyy")) {
			error("Date day not valid. Expected dd-MM-yyyy format", SchedulingPackage.Literals.DMY_DATE__DAY);
		}
		else if (!isValidDate("01-"+date.getMonth()+"-2000", "dd-MM-yyyy")) {
			error("Date month not valid. Expected dd-MM-yyyy format", SchedulingPackage.Literals.DMY_DATE__MONTH);
		}
		else if (!isValidDate("01-01-"+date.getYear(), "dd-MM-yyyy")) {
			error("Date year not valid. Expected dd-MM-yyyy format", SchedulingPackage.Literals.DMY_DATE__YEAR);
		}
		else if (date.getYear() < 1700 || date.getYear() > 2200) {
			error("Date year must be in range [1700, 2200]. Expected dd-MM-yyyy format", SchedulingPackage.Literals.DMY_DATE__YEAR);
		}
		else if (!isValidDate(dateStr, "dd-MM-yyyy")) {
			error("Date not valid. Expected dd-MM-yyyy format", SchedulingPackage.Literals.DMY_DATE__DAY);
		}
	}
	
	private boolean isValidDate(String date, String format) {
		try {
			DateFormat df = new SimpleDateFormat(format);
	        df.setLenient(false);
	        Date d = df.parse(date);
	        System.out.println(d.toGMTString());
	        return true;
	    } catch (ParseException e) {
	        return false;
	    }
	}
	
}
