/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SchedulingAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/uniovi/dsl/scheduling/parser/antlr/internal/InternalScheduling.tokens");
	}
}
