/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uniovi.dsl.scheduling.parser.antlr.internal.InternalSchedulingParser;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

public class SchedulingParser extends AbstractAntlrParser {

	@Inject
	private SchedulingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSchedulingParser createParser(XtextTokenStream stream) {
		return new InternalSchedulingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public SchedulingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchedulingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
