/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getInput <em>Input</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getRandomState <em>Random State</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getProbBeforeScheduling <em>Prob Before Scheduling</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getRateOfChange <em>Rate Of Change</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getDaysPerPeriod <em>Days Per Period</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getNumberOfPeriods <em>Number Of Periods</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getExtraHours <em>Extra Hours</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getMaxIters <em>Max Iters</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Config#getStartDate <em>Start Date</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig()
 * @model
 * @generated
 */
public interface Config extends EObject
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' attribute.
   * @see #setInput(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_Input()
   * @model
   * @generated
   */
  String getInput();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getInput <em>Input</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' attribute.
   * @see #getInput()
   * @generated
   */
  void setInput(String value);

  /**
   * Returns the value of the '<em><b>Random State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Random State</em>' attribute.
   * @see #setRandomState(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_RandomState()
   * @model
   * @generated
   */
  int getRandomState();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getRandomState <em>Random State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Random State</em>' attribute.
   * @see #getRandomState()
   * @generated
   */
  void setRandomState(int value);

  /**
   * Returns the value of the '<em><b>Prob Before Scheduling</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prob Before Scheduling</em>' attribute.
   * @see #setProbBeforeScheduling(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_ProbBeforeScheduling()
   * @model
   * @generated
   */
  String getProbBeforeScheduling();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getProbBeforeScheduling <em>Prob Before Scheduling</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prob Before Scheduling</em>' attribute.
   * @see #getProbBeforeScheduling()
   * @generated
   */
  void setProbBeforeScheduling(String value);

  /**
   * Returns the value of the '<em><b>Rate Of Change</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rate Of Change</em>' attribute.
   * @see #setRateOfChange(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_RateOfChange()
   * @model
   * @generated
   */
  String getRateOfChange();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getRateOfChange <em>Rate Of Change</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rate Of Change</em>' attribute.
   * @see #getRateOfChange()
   * @generated
   */
  void setRateOfChange(String value);

  /**
   * Returns the value of the '<em><b>Days Per Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Days Per Period</em>' attribute.
   * @see #setDaysPerPeriod(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_DaysPerPeriod()
   * @model
   * @generated
   */
  int getDaysPerPeriod();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getDaysPerPeriod <em>Days Per Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Days Per Period</em>' attribute.
   * @see #getDaysPerPeriod()
   * @generated
   */
  void setDaysPerPeriod(int value);

  /**
   * Returns the value of the '<em><b>Number Of Periods</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Of Periods</em>' attribute.
   * @see #setNumberOfPeriods(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_NumberOfPeriods()
   * @model
   * @generated
   */
  int getNumberOfPeriods();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getNumberOfPeriods <em>Number Of Periods</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number Of Periods</em>' attribute.
   * @see #getNumberOfPeriods()
   * @generated
   */
  void setNumberOfPeriods(int value);

  /**
   * Returns the value of the '<em><b>Extra Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extra Hours</em>' attribute.
   * @see #setExtraHours(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_ExtraHours()
   * @model
   * @generated
   */
  int getExtraHours();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getExtraHours <em>Extra Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extra Hours</em>' attribute.
   * @see #getExtraHours()
   * @generated
   */
  void setExtraHours(int value);

  /**
   * Returns the value of the '<em><b>Max Iters</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Iters</em>' attribute.
   * @see #setMaxIters(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_MaxIters()
   * @model
   * @generated
   */
  int getMaxIters();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getMaxIters <em>Max Iters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Iters</em>' attribute.
   * @see #getMaxIters()
   * @generated
   */
  void setMaxIters(int value);

  /**
   * Returns the value of the '<em><b>Start Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Date</em>' containment reference.
   * @see #setStartDate(DMYDate)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getConfig_StartDate()
   * @model containment="true"
   * @generated
   */
  DMYDate getStartDate();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Config#getStartDate <em>Start Date</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Date</em>' containment reference.
   * @see #getStartDate()
   * @generated
   */
  void setStartDate(DMYDate value);

} // Config
