/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getDate()
 * @model
 * @generated
 */
public interface Date extends EObject
{
} // Date
