/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DMY Date</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getDay <em>Day</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getMonth <em>Month</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getYear <em>Year</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getDMYDate()
 * @model
 * @generated
 */
public interface DMYDate extends Date
{
  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see #setDay(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getDMYDate_Day()
   * @model
   * @generated
   */
  int getDay();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see #getDay()
   * @generated
   */
  void setDay(int value);

  /**
   * Returns the value of the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Month</em>' attribute.
   * @see #setMonth(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getDMYDate_Month()
   * @model
   * @generated
   */
  int getMonth();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getMonth <em>Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Month</em>' attribute.
   * @see #getMonth()
   * @generated
   */
  void setMonth(int value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getDMYDate_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

} // DMYDate
