/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Installation Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getId <em>Id</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getInstallationName <em>Installation Name</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallationDef()
 * @model
 * @generated
 */
public interface InstallationDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallationDef_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Installation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Installation Name</em>' attribute.
   * @see #setInstallationName(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallationDef_InstallationName()
   * @model
   * @generated
   */
  String getInstallationName();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getInstallationName <em>Installation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Installation Name</em>' attribute.
   * @see #getInstallationName()
   * @generated
   */
  void setInstallationName(String value);

  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallationDef_Capacity()
   * @model
   * @generated
   */
  int getCapacity();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(int value);

} // InstallationDef
