/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maintenances</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Maintenances#getMaints <em>Maints</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintenances()
 * @model
 * @generated
 */
public interface Maintenances extends EObject
{
  /**
   * Returns the value of the '<em><b>Maints</b></em>' containment reference list.
   * The list contents are of type {@link org.uniovi.dsl.scheduling.scheduling.MaintDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maints</em>' containment reference list.
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintenances_Maints()
   * @model containment="true"
   * @generated
   */
  EList<MaintDef> getMaints();

} // Maintenances
