/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maint Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getId <em>Id</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getMaintName <em>Maint Name</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getHours <em>Hours</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getIncludes <em>Includes</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getInstallations <em>Installations</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef()
 * @model
 * @generated
 */
public interface MaintDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Maint Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maint Name</em>' attribute.
   * @see #setMaintName(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_MaintName()
   * @model
   * @generated
   */
  String getMaintName();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getMaintName <em>Maint Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maint Name</em>' attribute.
   * @see #getMaintName()
   * @generated
   */
  void setMaintName(String value);

  /**
   * Returns the value of the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hours</em>' attribute.
   * @see #setHours(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Hours()
   * @model
   * @generated
   */
  int getHours();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getHours <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hours</em>' attribute.
   * @see #getHours()
   * @generated
   */
  void setHours(int value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

  /**
   * Returns the value of the '<em><b>Includes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Includes</em>' attribute.
   * @see #setIncludes(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Includes()
   * @model
   * @generated
   */
  String getIncludes();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getIncludes <em>Includes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Includes</em>' attribute.
   * @see #getIncludes()
   * @generated
   */
  void setIncludes(String value);

  /**
   * Returns the value of the '<em><b>Installations</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Installations</em>' attribute.
   * @see #setInstallations(String)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getMaintDef_Installations()
   * @model
   * @generated
   */
  String getInstallations();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getInstallations <em>Installations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Installations</em>' attribute.
   * @see #getInstallations()
   * @generated
   */
  void setInstallations(String value);

} // MaintDef
