/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingFactory
 * @model kind="package"
 * @generated
 */
public interface SchedulingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "scheduling";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uniovi.org/dsl/scheduling/Scheduling";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "scheduling";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SchedulingPackage eINSTANCE = org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Installations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__INSTALLATIONS = 0;

  /**
   * The feature id for the '<em><b>Maintenances</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAINTENANCES = 1;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationsImpl <em>Installations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.InstallationsImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getInstallations()
   * @generated
   */
  int INSTALLATIONS = 1;

  /**
   * The feature id for the '<em><b>Installations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATIONS__INSTALLATIONS = 0;

  /**
   * The number of structural features of the '<em>Installations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl <em>Installation Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getInstallationDef()
   * @generated
   */
  int INSTALLATION_DEF = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_DEF__ID = 0;

  /**
   * The feature id for the '<em><b>Installation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_DEF__INSTALLATION_NAME = 1;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_DEF__CAPACITY = 2;

  /**
   * The number of structural features of the '<em>Installation Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_DEF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintenancesImpl <em>Maintenances</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.MaintenancesImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getMaintenances()
   * @generated
   */
  int MAINTENANCES = 3;

  /**
   * The feature id for the '<em><b>Maints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINTENANCES__MAINTS = 0;

  /**
   * The number of structural features of the '<em>Maintenances</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINTENANCES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl <em>Maint Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getMaintDef()
   * @generated
   */
  int MAINT_DEF = 4;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__ID = 0;

  /**
   * The feature id for the '<em><b>Maint Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__MAINT_NAME = 1;

  /**
   * The feature id for the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__HOURS = 2;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__DURATION = 3;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__PRIORITY = 4;

  /**
   * The feature id for the '<em><b>Includes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__INCLUDES = 5;

  /**
   * The feature id for the '<em><b>Installations</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF__INSTALLATIONS = 6;

  /**
   * The number of structural features of the '<em>Maint Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINT_DEF_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl <em>Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getConfig()
   * @generated
   */
  int CONFIG = 5;

  /**
   * The feature id for the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__INPUT = 0;

  /**
   * The feature id for the '<em><b>Random State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__RANDOM_STATE = 1;

  /**
   * The feature id for the '<em><b>Prob Before Scheduling</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__PROB_BEFORE_SCHEDULING = 2;

  /**
   * The feature id for the '<em><b>Rate Of Change</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__RATE_OF_CHANGE = 3;

  /**
   * The feature id for the '<em><b>Days Per Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__DAYS_PER_PERIOD = 4;

  /**
   * The feature id for the '<em><b>Number Of Periods</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__NUMBER_OF_PERIODS = 5;

  /**
   * The feature id for the '<em><b>Extra Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__EXTRA_HOURS = 6;

  /**
   * The feature id for the '<em><b>Max Iters</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__MAX_ITERS = 7;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__START_DATE = 8;

  /**
   * The number of structural features of the '<em>Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.DateImpl <em>Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.DateImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getDate()
   * @generated
   */
  int DATE = 6;

  /**
   * The number of structural features of the '<em>Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.DMYDateImpl <em>DMY Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uniovi.dsl.scheduling.scheduling.impl.DMYDateImpl
   * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getDMYDate()
   * @generated
   */
  int DMY_DATE = 7;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DMY_DATE__DAY = DATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DMY_DATE__MONTH = DATE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DMY_DATE__YEAR = DATE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>DMY Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DMY_DATE_FEATURE_COUNT = DATE_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link org.uniovi.dsl.scheduling.scheduling.Program#getInstallations <em>Installations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Installations</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Program#getInstallations()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Installations();

  /**
   * Returns the meta object for the containment reference '{@link org.uniovi.dsl.scheduling.scheduling.Program#getMaintenances <em>Maintenances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Maintenances</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Program#getMaintenances()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Maintenances();

  /**
   * Returns the meta object for the containment reference '{@link org.uniovi.dsl.scheduling.scheduling.Program#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Options</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Program#getOptions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Options();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.Installations <em>Installations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Installations</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Installations
   * @generated
   */
  EClass getInstallations();

  /**
   * Returns the meta object for the containment reference list '{@link org.uniovi.dsl.scheduling.scheduling.Installations#getInstallations <em>Installations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Installations</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Installations#getInstallations()
   * @see #getInstallations()
   * @generated
   */
  EReference getInstallations_Installations();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef <em>Installation Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Installation Def</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.InstallationDef
   * @generated
   */
  EClass getInstallationDef();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.InstallationDef#getId()
   * @see #getInstallationDef()
   * @generated
   */
  EAttribute getInstallationDef_Id();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getInstallationName <em>Installation Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Installation Name</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.InstallationDef#getInstallationName()
   * @see #getInstallationDef()
   * @generated
   */
  EAttribute getInstallationDef_InstallationName();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.InstallationDef#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.InstallationDef#getCapacity()
   * @see #getInstallationDef()
   * @generated
   */
  EAttribute getInstallationDef_Capacity();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.Maintenances <em>Maintenances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maintenances</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Maintenances
   * @generated
   */
  EClass getMaintenances();

  /**
   * Returns the meta object for the containment reference list '{@link org.uniovi.dsl.scheduling.scheduling.Maintenances#getMaints <em>Maints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Maints</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Maintenances#getMaints()
   * @see #getMaintenances()
   * @generated
   */
  EReference getMaintenances_Maints();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef <em>Maint Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maint Def</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef
   * @generated
   */
  EClass getMaintDef();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getId()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Id();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getMaintName <em>Maint Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Maint Name</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getMaintName()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_MaintName();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getHours <em>Hours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hours</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getHours()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Hours();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getDuration()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getPriority()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Priority();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getIncludes <em>Includes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Includes</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getIncludes()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Includes();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.MaintDef#getInstallations <em>Installations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Installations</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.MaintDef#getInstallations()
   * @see #getMaintDef()
   * @generated
   */
  EAttribute getMaintDef_Installations();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.Config <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config
   * @generated
   */
  EClass getConfig();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getInput()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_Input();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getRandomState <em>Random State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Random State</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getRandomState()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_RandomState();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getProbBeforeScheduling <em>Prob Before Scheduling</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prob Before Scheduling</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getProbBeforeScheduling()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_ProbBeforeScheduling();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getRateOfChange <em>Rate Of Change</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rate Of Change</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getRateOfChange()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_RateOfChange();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getDaysPerPeriod <em>Days Per Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Days Per Period</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getDaysPerPeriod()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_DaysPerPeriod();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getNumberOfPeriods <em>Number Of Periods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number Of Periods</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getNumberOfPeriods()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_NumberOfPeriods();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getExtraHours <em>Extra Hours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Extra Hours</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getExtraHours()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_ExtraHours();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.Config#getMaxIters <em>Max Iters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Iters</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getMaxIters()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_MaxIters();

  /**
   * Returns the meta object for the containment reference '{@link org.uniovi.dsl.scheduling.scheduling.Config#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Start Date</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Config#getStartDate()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_StartDate();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.Date <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.Date
   * @generated
   */
  EClass getDate();

  /**
   * Returns the meta object for class '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate <em>DMY Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DMY Date</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.DMYDate
   * @generated
   */
  EClass getDMYDate();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.DMYDate#getDay()
   * @see #getDMYDate()
   * @generated
   */
  EAttribute getDMYDate_Day();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getMonth <em>Month</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Month</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.DMYDate#getMonth()
   * @see #getDMYDate()
   * @generated
   */
  EAttribute getDMYDate_Month();

  /**
   * Returns the meta object for the attribute '{@link org.uniovi.dsl.scheduling.scheduling.DMYDate#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.uniovi.dsl.scheduling.scheduling.DMYDate#getYear()
   * @see #getDMYDate()
   * @generated
   */
  EAttribute getDMYDate_Year();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SchedulingFactory getSchedulingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Installations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__INSTALLATIONS = eINSTANCE.getProgram_Installations();

    /**
     * The meta object literal for the '<em><b>Maintenances</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAINTENANCES = eINSTANCE.getProgram_Maintenances();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__OPTIONS = eINSTANCE.getProgram_Options();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationsImpl <em>Installations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.InstallationsImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getInstallations()
     * @generated
     */
    EClass INSTALLATIONS = eINSTANCE.getInstallations();

    /**
     * The meta object literal for the '<em><b>Installations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTALLATIONS__INSTALLATIONS = eINSTANCE.getInstallations_Installations();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl <em>Installation Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getInstallationDef()
     * @generated
     */
    EClass INSTALLATION_DEF = eINSTANCE.getInstallationDef();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTALLATION_DEF__ID = eINSTANCE.getInstallationDef_Id();

    /**
     * The meta object literal for the '<em><b>Installation Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTALLATION_DEF__INSTALLATION_NAME = eINSTANCE.getInstallationDef_InstallationName();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTALLATION_DEF__CAPACITY = eINSTANCE.getInstallationDef_Capacity();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintenancesImpl <em>Maintenances</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.MaintenancesImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getMaintenances()
     * @generated
     */
    EClass MAINTENANCES = eINSTANCE.getMaintenances();

    /**
     * The meta object literal for the '<em><b>Maints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAINTENANCES__MAINTS = eINSTANCE.getMaintenances_Maints();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl <em>Maint Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getMaintDef()
     * @generated
     */
    EClass MAINT_DEF = eINSTANCE.getMaintDef();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__ID = eINSTANCE.getMaintDef_Id();

    /**
     * The meta object literal for the '<em><b>Maint Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__MAINT_NAME = eINSTANCE.getMaintDef_MaintName();

    /**
     * The meta object literal for the '<em><b>Hours</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__HOURS = eINSTANCE.getMaintDef_Hours();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__DURATION = eINSTANCE.getMaintDef_Duration();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__PRIORITY = eINSTANCE.getMaintDef_Priority();

    /**
     * The meta object literal for the '<em><b>Includes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__INCLUDES = eINSTANCE.getMaintDef_Includes();

    /**
     * The meta object literal for the '<em><b>Installations</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINT_DEF__INSTALLATIONS = eINSTANCE.getMaintDef_Installations();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl <em>Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getConfig()
     * @generated
     */
    EClass CONFIG = eINSTANCE.getConfig();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__INPUT = eINSTANCE.getConfig_Input();

    /**
     * The meta object literal for the '<em><b>Random State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__RANDOM_STATE = eINSTANCE.getConfig_RandomState();

    /**
     * The meta object literal for the '<em><b>Prob Before Scheduling</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__PROB_BEFORE_SCHEDULING = eINSTANCE.getConfig_ProbBeforeScheduling();

    /**
     * The meta object literal for the '<em><b>Rate Of Change</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__RATE_OF_CHANGE = eINSTANCE.getConfig_RateOfChange();

    /**
     * The meta object literal for the '<em><b>Days Per Period</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__DAYS_PER_PERIOD = eINSTANCE.getConfig_DaysPerPeriod();

    /**
     * The meta object literal for the '<em><b>Number Of Periods</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__NUMBER_OF_PERIODS = eINSTANCE.getConfig_NumberOfPeriods();

    /**
     * The meta object literal for the '<em><b>Extra Hours</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__EXTRA_HOURS = eINSTANCE.getConfig_ExtraHours();

    /**
     * The meta object literal for the '<em><b>Max Iters</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__MAX_ITERS = eINSTANCE.getConfig_MaxIters();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__START_DATE = eINSTANCE.getConfig_StartDate();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.DateImpl <em>Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.DateImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getDate()
     * @generated
     */
    EClass DATE = eINSTANCE.getDate();

    /**
     * The meta object literal for the '{@link org.uniovi.dsl.scheduling.scheduling.impl.DMYDateImpl <em>DMY Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uniovi.dsl.scheduling.scheduling.impl.DMYDateImpl
     * @see org.uniovi.dsl.scheduling.scheduling.impl.SchedulingPackageImpl#getDMYDate()
     * @generated
     */
    EClass DMY_DATE = eINSTANCE.getDMYDate();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DMY_DATE__DAY = eINSTANCE.getDMYDate_Day();

    /**
     * The meta object literal for the '<em><b>Month</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DMY_DATE__MONTH = eINSTANCE.getDMYDate_Month();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DMY_DATE__YEAR = eINSTANCE.getDMYDate_Year();

  }

} //SchedulingPackage
