/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.uniovi.dsl.scheduling.SchedulingRuntimeModule;
import org.uniovi.dsl.scheduling.SchedulingStandaloneSetup;
import org.uniovi.dsl.scheduling.ide.SchedulingIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SchedulingWebSetup extends SchedulingStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SchedulingRuntimeModule(), new SchedulingIdeModule(), new SchedulingWebModule()));
	}
	
}
