/*
 * generated by Xtext 2.31.0
 */
grammar InternalScheduling;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.uniovi.dsl.scheduling.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.uniovi.dsl.scheduling.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

}
@parser::members {
	private SchedulingGrammarAccess grammarAccess;

	public void setGrammarAccess(SchedulingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleProgram
entryRuleProgram
:
{ before(grammarAccess.getProgramRule()); }
	 ruleProgram
{ after(grammarAccess.getProgramRule()); } 
	 EOF 
;

// Rule Program
ruleProgram 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getProgramAccess().getUnorderedGroup()); }
		(rule__Program__UnorderedGroup)
		{ after(grammarAccess.getProgramAccess().getUnorderedGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInstallations
entryRuleInstallations
:
{ before(grammarAccess.getInstallationsRule()); }
	 ruleInstallations
{ after(grammarAccess.getInstallationsRule()); } 
	 EOF 
;

// Rule Installations
ruleInstallations 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInstallationsAccess().getGroup()); }
		(rule__Installations__Group__0)
		{ after(grammarAccess.getInstallationsAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInstallationDef
entryRuleInstallationDef
:
{ before(grammarAccess.getInstallationDefRule()); }
	 ruleInstallationDef
{ after(grammarAccess.getInstallationDefRule()); } 
	 EOF 
;

// Rule InstallationDef
ruleInstallationDef 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInstallationDefAccess().getGroup()); }
		(rule__InstallationDef__Group__0)
		{ after(grammarAccess.getInstallationDefAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMaintenances
entryRuleMaintenances
:
{ before(grammarAccess.getMaintenancesRule()); }
	 ruleMaintenances
{ after(grammarAccess.getMaintenancesRule()); } 
	 EOF 
;

// Rule Maintenances
ruleMaintenances 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMaintenancesAccess().getGroup()); }
		(rule__Maintenances__Group__0)
		{ after(grammarAccess.getMaintenancesAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMaintDef
entryRuleMaintDef
:
{ before(grammarAccess.getMaintDefRule()); }
	 ruleMaintDef
{ after(grammarAccess.getMaintDefRule()); } 
	 EOF 
;

// Rule MaintDef
ruleMaintDef 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMaintDefAccess().getGroup()); }
		(rule__MaintDef__Group__0)
		{ after(grammarAccess.getMaintDefAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleConfig
entryRuleConfig
:
{ before(grammarAccess.getConfigRule()); }
	 ruleConfig
{ after(grammarAccess.getConfigRule()); } 
	 EOF 
;

// Rule Config
ruleConfig 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getConfigAccess().getGroup()); }
		(rule__Config__Group__0)
		{ after(grammarAccess.getConfigAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleList
entryRuleList
:
{ before(grammarAccess.getListRule()); }
	 ruleList
{ after(grammarAccess.getListRule()); } 
	 EOF 
;

// Rule List
ruleList 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getListAccess().getGroup()); }
		(rule__List__Group__0)
		{ after(grammarAccess.getListAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Installations__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Installations__Group__0__Impl
	rule__Installations__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Installations__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationsAccess().getINSTALLATIONS_HEADERTerminalRuleCall_0()); }
	RULE_INSTALLATIONS_HEADER
	{ after(grammarAccess.getInstallationsAccess().getINSTALLATIONS_HEADERTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Installations__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Installations__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Installations__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getInstallationsAccess().getInstallationsAssignment_1()); }
		(rule__Installations__InstallationsAssignment_1)
		{ after(grammarAccess.getInstallationsAccess().getInstallationsAssignment_1()); }
	)
	(
		{ before(grammarAccess.getInstallationsAccess().getInstallationsAssignment_1()); }
		(rule__Installations__InstallationsAssignment_1)*
		{ after(grammarAccess.getInstallationsAccess().getInstallationsAssignment_1()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InstallationDef__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group__0__Impl
	rule__InstallationDef__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getINSTALLATION_TYPETerminalRuleCall_0()); }
	RULE_INSTALLATION_TYPE
	{ after(grammarAccess.getInstallationDefAccess().getINSTALLATION_TYPETerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group__1__Impl
	rule__InstallationDef__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getIdAssignment_1()); }
	(rule__InstallationDef__IdAssignment_1)
	{ after(grammarAccess.getInstallationDefAccess().getIdAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2()); }
	(rule__InstallationDef__UnorderedGroup_2)
	{ after(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InstallationDef__Group_2_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group_2_0__0__Impl
	rule__InstallationDef__Group_2_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getNameKeyword_2_0_0()); }
	'Name:'
	{ after(grammarAccess.getInstallationDefAccess().getNameKeyword_2_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group_2_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getInstallationNameAssignment_2_0_1()); }
	(rule__InstallationDef__InstallationNameAssignment_2_0_1)
	{ after(grammarAccess.getInstallationDefAccess().getInstallationNameAssignment_2_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InstallationDef__Group_2_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group_2_1__0__Impl
	rule__InstallationDef__Group_2_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getCapacityKeyword_2_1_0()); }
	'Capacity:'
	{ after(grammarAccess.getInstallationDefAccess().getCapacityKeyword_2_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__Group_2_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__Group_2_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInstallationDefAccess().getCapacityAssignment_2_1_1()); }
	(rule__InstallationDef__CapacityAssignment_2_1_1)
	{ after(grammarAccess.getInstallationDefAccess().getCapacityAssignment_2_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Maintenances__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Maintenances__Group__0__Impl
	rule__Maintenances__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Maintenances__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintenancesAccess().getMAINTENANCES_HEADERTerminalRuleCall_0()); }
	RULE_MAINTENANCES_HEADER
	{ after(grammarAccess.getMaintenancesAccess().getMAINTENANCES_HEADERTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Maintenances__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Maintenances__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Maintenances__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getMaintenancesAccess().getMaintsAssignment_1()); }
		(rule__Maintenances__MaintsAssignment_1)
		{ after(grammarAccess.getMaintenancesAccess().getMaintsAssignment_1()); }
	)
	(
		{ before(grammarAccess.getMaintenancesAccess().getMaintsAssignment_1()); }
		(rule__Maintenances__MaintsAssignment_1)*
		{ after(grammarAccess.getMaintenancesAccess().getMaintsAssignment_1()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group__0__Impl
	rule__MaintDef__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getMAINTENANCE_TYPETerminalRuleCall_0()); }
	RULE_MAINTENANCE_TYPE
	{ after(grammarAccess.getMaintDefAccess().getMAINTENANCE_TYPETerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group__1__Impl
	rule__MaintDef__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getIdAssignment_1()); }
	(rule__MaintDef__IdAssignment_1)
	{ after(grammarAccess.getMaintDefAccess().getIdAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getUnorderedGroup_2()); }
	(rule__MaintDef__UnorderedGroup_2)
	{ after(grammarAccess.getMaintDefAccess().getUnorderedGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_0__0__Impl
	rule__MaintDef__Group_2_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getNameKeyword_2_0_0()); }
	'Name:'
	{ after(grammarAccess.getMaintDefAccess().getNameKeyword_2_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getMaintNameAssignment_2_0_1()); }
	(rule__MaintDef__MaintNameAssignment_2_0_1)
	{ after(grammarAccess.getMaintDefAccess().getMaintNameAssignment_2_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_1__0__Impl
	rule__MaintDef__Group_2_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getIntervalKeyword_2_1_0()); }
	'Interval:'
	{ after(grammarAccess.getMaintDefAccess().getIntervalKeyword_2_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getHoursAssignment_2_1_1()); }
	(rule__MaintDef__HoursAssignment_2_1_1)
	{ after(grammarAccess.getMaintDefAccess().getHoursAssignment_2_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_2__0__Impl
	rule__MaintDef__Group_2_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getPeriodsKeyword_2_2_0()); }
	'Periods:'
	{ after(grammarAccess.getMaintDefAccess().getPeriodsKeyword_2_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getDurationAssignment_2_2_1()); }
	(rule__MaintDef__DurationAssignment_2_2_1)
	{ after(grammarAccess.getMaintDefAccess().getDurationAssignment_2_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_3__0__Impl
	rule__MaintDef__Group_2_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getPriorityKeyword_2_3_0()); }
	'Priority:'
	{ after(grammarAccess.getMaintDefAccess().getPriorityKeyword_2_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getPriorityAssignment_2_3_1()); }
	(rule__MaintDef__PriorityAssignment_2_3_1)
	{ after(grammarAccess.getMaintDefAccess().getPriorityAssignment_2_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_4__0__Impl
	rule__MaintDef__Group_2_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getIncludesKeyword_2_4_0()); }
	'Includes:'
	{ after(grammarAccess.getMaintDefAccess().getIncludesKeyword_2_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getIncludesAssignment_2_4_1()); }
	(rule__MaintDef__IncludesAssignment_2_4_1)
	{ after(grammarAccess.getMaintDefAccess().getIncludesAssignment_2_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__Group_2_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_5__0__Impl
	rule__MaintDef__Group_2_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getInstallationsKeyword_2_5_0()); }
	'Installations:'
	{ after(grammarAccess.getMaintDefAccess().getInstallationsKeyword_2_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__Group_2_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__Group_2_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMaintDefAccess().getInstallationsAssignment_2_5_1()); }
	(rule__MaintDef__InstallationsAssignment_2_5_1)
	{ after(grammarAccess.getMaintDefAccess().getInstallationsAssignment_2_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group__0__Impl
	rule__Config__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getOPTIONS_HEADERTerminalRuleCall_0()); }
	RULE_OPTIONS_HEADER
	{ after(grammarAccess.getConfigAccess().getOPTIONS_HEADERTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getUnorderedGroup_1()); }
	(rule__Config__UnorderedGroup_1)
	{ after(grammarAccess.getConfigAccess().getUnorderedGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_0__0__Impl
	rule__Config__Group_1_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getInputKeyword_1_0_0()); }
	'Input:'
	{ after(grammarAccess.getConfigAccess().getInputKeyword_1_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getInputAssignment_1_0_1()); }
	(rule__Config__InputAssignment_1_0_1)
	{ after(grammarAccess.getConfigAccess().getInputAssignment_1_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_1__0__Impl
	rule__Config__Group_1_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getRandom_stateKeyword_1_1_0()); }
	'Random_state:'
	{ after(grammarAccess.getConfigAccess().getRandom_stateKeyword_1_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getRandomStateAssignment_1_1_1()); }
	(rule__Config__RandomStateAssignment_1_1_1)
	{ after(grammarAccess.getConfigAccess().getRandomStateAssignment_1_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_2__0__Impl
	rule__Config__Group_1_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getProb_before_restrictionKeyword_1_2_0()); }
	'Prob_before_restriction:'
	{ after(grammarAccess.getConfigAccess().getProb_before_restrictionKeyword_1_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getProbBeforeSchedulingAssignment_1_2_1()); }
	(rule__Config__ProbBeforeSchedulingAssignment_1_2_1)
	{ after(grammarAccess.getConfigAccess().getProbBeforeSchedulingAssignment_1_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_3__0__Impl
	rule__Config__Group_1_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getRate_of_changeKeyword_1_3_0()); }
	'Rate_of_change:'
	{ after(grammarAccess.getConfigAccess().getRate_of_changeKeyword_1_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getRateOfChangeAssignment_1_3_1()); }
	(rule__Config__RateOfChangeAssignment_1_3_1)
	{ after(grammarAccess.getConfigAccess().getRateOfChangeAssignment_1_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_4__0__Impl
	rule__Config__Group_1_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getDays_per_periodKeyword_1_4_0()); }
	'Days_per_period:'
	{ after(grammarAccess.getConfigAccess().getDays_per_periodKeyword_1_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getDaysPerPeriodAssignment_1_4_1()); }
	(rule__Config__DaysPerPeriodAssignment_1_4_1)
	{ after(grammarAccess.getConfigAccess().getDaysPerPeriodAssignment_1_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_5__0__Impl
	rule__Config__Group_1_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getNumber_of_periodsKeyword_1_5_0()); }
	'Number_of_periods:'
	{ after(grammarAccess.getConfigAccess().getNumber_of_periodsKeyword_1_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getNumberOfPeriodsAssignment_1_5_1()); }
	(rule__Config__NumberOfPeriodsAssignment_1_5_1)
	{ after(grammarAccess.getConfigAccess().getNumberOfPeriodsAssignment_1_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_6__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_6__0__Impl
	rule__Config__Group_1_6__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_6__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getExtra_hoursKeyword_1_6_0()); }
	'Extra_hours:'
	{ after(grammarAccess.getConfigAccess().getExtra_hoursKeyword_1_6_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_6__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_6__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_6__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getExtraHoursAssignment_1_6_1()); }
	(rule__Config__ExtraHoursAssignment_1_6_1)
	{ after(grammarAccess.getConfigAccess().getExtraHoursAssignment_1_6_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__Group_1_7__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_7__0__Impl
	rule__Config__Group_1_7__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_7__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getIterationsKeyword_1_7_0()); }
	'Iterations:'
	{ after(grammarAccess.getConfigAccess().getIterationsKeyword_1_7_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_7__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__Group_1_7__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__Group_1_7__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getConfigAccess().getMaxItersAssignment_1_7_1()); }
	(rule__Config__MaxItersAssignment_1_7_1)
	{ after(grammarAccess.getConfigAccess().getMaxItersAssignment_1_7_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__List__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__List__Group__0__Impl
	rule__List__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getListAccess().getIDTerminalRuleCall_0()); }
	RULE_ID
	{ after(grammarAccess.getListAccess().getIDTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__List__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getListAccess().getGroup_1()); }
	(rule__List__Group_1__0)*
	{ after(grammarAccess.getListAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__List__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__List__Group_1__0__Impl
	rule__List__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getListAccess().getCommaKeyword_1_0()); }
	','
	{ after(grammarAccess.getListAccess().getCommaKeyword_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__List__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__List__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getListAccess().getIDTerminalRuleCall_1_1()); }
	RULE_ID
	{ after(grammarAccess.getListAccess().getIDTerminalRuleCall_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Program__UnorderedGroup
	@init {
		int stackSize = keepStackSize();
		getUnorderedGroupHelper().enter(grammarAccess.getProgramAccess().getUnorderedGroup());
	}
:
	rule__Program__UnorderedGroup__0
	{getUnorderedGroupHelper().canLeave(grammarAccess.getProgramAccess().getUnorderedGroup())}?
;
finally {
	getUnorderedGroupHelper().leave(grammarAccess.getProgramAccess().getUnorderedGroup());
	restoreStackSize(stackSize);
}

rule__Program__UnorderedGroup__Impl
	@init {
		int stackSize = keepStackSize();
		boolean selected = false;
	}
:
		(
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 0);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getProgramAccess().getInstallationsAssignment_0()); }
					(rule__Program__InstallationsAssignment_0)
					{ after(grammarAccess.getProgramAccess().getInstallationsAssignment_0()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 1);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getProgramAccess().getMaintenancesAssignment_1()); }
					(rule__Program__MaintenancesAssignment_1)
					{ after(grammarAccess.getProgramAccess().getMaintenancesAssignment_1()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getProgramAccess().getUnorderedGroup(), 2)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getProgramAccess().getUnorderedGroup(), 2);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getProgramAccess().getOptionsAssignment_2()); }
					(rule__Program__OptionsAssignment_2)
					{ after(grammarAccess.getProgramAccess().getOptionsAssignment_2()); }
				)
			)
		)
		)
;
finally {
	if (selected)
		getUnorderedGroupHelper().returnFromSelection(grammarAccess.getProgramAccess().getUnorderedGroup());
	restoreStackSize(stackSize);
}

rule__Program__UnorderedGroup__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Program__UnorderedGroup__Impl
	rule__Program__UnorderedGroup__1?
;
finally {
	restoreStackSize(stackSize);
}

rule__Program__UnorderedGroup__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Program__UnorderedGroup__Impl
	rule__Program__UnorderedGroup__2?
;
finally {
	restoreStackSize(stackSize);
}

rule__Program__UnorderedGroup__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Program__UnorderedGroup__Impl
;
finally {
	restoreStackSize(stackSize);
}


rule__InstallationDef__UnorderedGroup_2
	@init {
		int stackSize = keepStackSize();
		getUnorderedGroupHelper().enter(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
	}
:
	rule__InstallationDef__UnorderedGroup_2__0
	{getUnorderedGroupHelper().canLeave(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2())}?
;
finally {
	getUnorderedGroupHelper().leave(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
	restoreStackSize(stackSize);
}

rule__InstallationDef__UnorderedGroup_2__Impl
	@init {
		int stackSize = keepStackSize();
		boolean selected = false;
	}
:
		(
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 0);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getInstallationDefAccess().getGroup_2_0()); }
					(rule__InstallationDef__Group_2_0__0)
					{ after(grammarAccess.getInstallationDefAccess().getGroup_2_0()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), 1);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getInstallationDefAccess().getGroup_2_1()); }
					(rule__InstallationDef__Group_2_1__0)
					{ after(grammarAccess.getInstallationDefAccess().getGroup_2_1()); }
				)
			)
		)
		)
;
finally {
	if (selected)
		getUnorderedGroupHelper().returnFromSelection(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2());
	restoreStackSize(stackSize);
}

rule__InstallationDef__UnorderedGroup_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__UnorderedGroup_2__Impl
	rule__InstallationDef__UnorderedGroup_2__1?
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__UnorderedGroup_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InstallationDef__UnorderedGroup_2__Impl
;
finally {
	restoreStackSize(stackSize);
}


rule__MaintDef__UnorderedGroup_2
	@init {
		int stackSize = keepStackSize();
		getUnorderedGroupHelper().enter(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
	}
:
	rule__MaintDef__UnorderedGroup_2__0
	{getUnorderedGroupHelper().canLeave(grammarAccess.getMaintDefAccess().getUnorderedGroup_2())}?
;
finally {
	getUnorderedGroupHelper().leave(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__Impl
	@init {
		int stackSize = keepStackSize();
		boolean selected = false;
	}
:
		(
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 0);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_0()); }
					(rule__MaintDef__Group_2_0__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_0()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 1);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_1()); }
					(rule__MaintDef__Group_2_1__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_1()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 2)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 2);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_2()); }
					(rule__MaintDef__Group_2_2__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_2()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 3)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 3);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_3()); }
					(rule__MaintDef__Group_2_3__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_3()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 4)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 4);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_4()); }
					(rule__MaintDef__Group_2_4__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_4()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 5)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), 5);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getMaintDefAccess().getGroup_2_5()); }
					(rule__MaintDef__Group_2_5__0)
					{ after(grammarAccess.getMaintDefAccess().getGroup_2_5()); }
				)
			)
		)
		)
;
finally {
	if (selected)
		getUnorderedGroupHelper().returnFromSelection(grammarAccess.getMaintDefAccess().getUnorderedGroup_2());
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
	rule__MaintDef__UnorderedGroup_2__1?
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
	rule__MaintDef__UnorderedGroup_2__2?
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
	rule__MaintDef__UnorderedGroup_2__3?
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
	rule__MaintDef__UnorderedGroup_2__4?
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
	rule__MaintDef__UnorderedGroup_2__5?
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__UnorderedGroup_2__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MaintDef__UnorderedGroup_2__Impl
;
finally {
	restoreStackSize(stackSize);
}


rule__Config__UnorderedGroup_1
	@init {
		int stackSize = keepStackSize();
		getUnorderedGroupHelper().enter(grammarAccess.getConfigAccess().getUnorderedGroup_1());
	}
:
	rule__Config__UnorderedGroup_1__0
	{getUnorderedGroupHelper().canLeave(grammarAccess.getConfigAccess().getUnorderedGroup_1())}?
;
finally {
	getUnorderedGroupHelper().leave(grammarAccess.getConfigAccess().getUnorderedGroup_1());
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__Impl
	@init {
		int stackSize = keepStackSize();
		boolean selected = false;
	}
:
		(
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 0);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_0()); }
					(rule__Config__Group_1_0__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_0()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 1);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_1()); }
					(rule__Config__Group_1_1__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_1()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 2)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 2);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_2()); }
					(rule__Config__Group_1_2__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_2()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 3)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 3);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_3()); }
					(rule__Config__Group_1_3__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_3()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 4)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 4);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_4()); }
					(rule__Config__Group_1_4__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_4()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 5)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 5);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_5()); }
					(rule__Config__Group_1_5__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_5()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 6)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 6);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_6()); }
					(rule__Config__Group_1_6__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_6()); }
				)
			)
		)|
		( 
			{getUnorderedGroupHelper().canSelect(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 7)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getConfigAccess().getUnorderedGroup_1(), 7);
				}
				{
					selected = true;
				}
				(
					{ before(grammarAccess.getConfigAccess().getGroup_1_7()); }
					(rule__Config__Group_1_7__0)
					{ after(grammarAccess.getConfigAccess().getGroup_1_7()); }
				)
			)
		)
		)
;
finally {
	if (selected)
		getUnorderedGroupHelper().returnFromSelection(grammarAccess.getConfigAccess().getUnorderedGroup_1());
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__1?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__2?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__3?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__4?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__5?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__6?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
	rule__Config__UnorderedGroup_1__7?
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__UnorderedGroup_1__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Config__UnorderedGroup_1__Impl
;
finally {
	restoreStackSize(stackSize);
}


rule__Program__InstallationsAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProgramAccess().getInstallationsInstallationsParserRuleCall_0_0()); }
		ruleInstallations
		{ after(grammarAccess.getProgramAccess().getInstallationsInstallationsParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Program__MaintenancesAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProgramAccess().getMaintenancesMaintenancesParserRuleCall_1_0()); }
		ruleMaintenances
		{ after(grammarAccess.getProgramAccess().getMaintenancesMaintenancesParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Program__OptionsAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProgramAccess().getOptionsConfigParserRuleCall_2_0()); }
		ruleConfig
		{ after(grammarAccess.getProgramAccess().getOptionsConfigParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Installations__InstallationsAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstallationsAccess().getInstallationsInstallationDefParserRuleCall_1_0()); }
		ruleInstallationDef
		{ after(grammarAccess.getInstallationsAccess().getInstallationsInstallationDefParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__IdAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstallationDefAccess().getIdIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getInstallationDefAccess().getIdIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__InstallationNameAssignment_2_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstallationDefAccess().getInstallationNameSTRINGTerminalRuleCall_2_0_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getInstallationDefAccess().getInstallationNameSTRINGTerminalRuleCall_2_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InstallationDef__CapacityAssignment_2_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstallationDefAccess().getCapacityINTTerminalRuleCall_2_1_1_0()); }
		RULE_INT
		{ after(grammarAccess.getInstallationDefAccess().getCapacityINTTerminalRuleCall_2_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Maintenances__MaintsAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintenancesAccess().getMaintsMaintDefParserRuleCall_1_0()); }
		ruleMaintDef
		{ after(grammarAccess.getMaintenancesAccess().getMaintsMaintDefParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__IdAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getIdIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getMaintDefAccess().getIdIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__MaintNameAssignment_2_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getMaintNameSTRINGTerminalRuleCall_2_0_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getMaintDefAccess().getMaintNameSTRINGTerminalRuleCall_2_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__HoursAssignment_2_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getHoursINTTerminalRuleCall_2_1_1_0()); }
		RULE_INT
		{ after(grammarAccess.getMaintDefAccess().getHoursINTTerminalRuleCall_2_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__DurationAssignment_2_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getDurationINTTerminalRuleCall_2_2_1_0()); }
		RULE_INT
		{ after(grammarAccess.getMaintDefAccess().getDurationINTTerminalRuleCall_2_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__PriorityAssignment_2_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getPriorityINTTerminalRuleCall_2_3_1_0()); }
		RULE_INT
		{ after(grammarAccess.getMaintDefAccess().getPriorityINTTerminalRuleCall_2_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__IncludesAssignment_2_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getIncludesListParserRuleCall_2_4_1_0()); }
		ruleList
		{ after(grammarAccess.getMaintDefAccess().getIncludesListParserRuleCall_2_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MaintDef__InstallationsAssignment_2_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMaintDefAccess().getInstallationsListParserRuleCall_2_5_1_0()); }
		ruleList
		{ after(grammarAccess.getMaintDefAccess().getInstallationsListParserRuleCall_2_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__InputAssignment_1_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getInputSTRINGTerminalRuleCall_1_0_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getConfigAccess().getInputSTRINGTerminalRuleCall_1_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__RandomStateAssignment_1_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getRandomStateINTTerminalRuleCall_1_1_1_0()); }
		RULE_INT
		{ after(grammarAccess.getConfigAccess().getRandomStateINTTerminalRuleCall_1_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__ProbBeforeSchedulingAssignment_1_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0()); }
		RULE_FLOAT
		{ after(grammarAccess.getConfigAccess().getProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__RateOfChangeAssignment_1_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getRateOfChangeFLOATTerminalRuleCall_1_3_1_0()); }
		RULE_FLOAT
		{ after(grammarAccess.getConfigAccess().getRateOfChangeFLOATTerminalRuleCall_1_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__DaysPerPeriodAssignment_1_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getDaysPerPeriodINTTerminalRuleCall_1_4_1_0()); }
		RULE_INT
		{ after(grammarAccess.getConfigAccess().getDaysPerPeriodINTTerminalRuleCall_1_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__NumberOfPeriodsAssignment_1_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getNumberOfPeriodsINTTerminalRuleCall_1_5_1_0()); }
		RULE_INT
		{ after(grammarAccess.getConfigAccess().getNumberOfPeriodsINTTerminalRuleCall_1_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__ExtraHoursAssignment_1_6_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getExtraHoursINTTerminalRuleCall_1_6_1_0()); }
		RULE_INT
		{ after(grammarAccess.getConfigAccess().getExtraHoursINTTerminalRuleCall_1_6_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Config__MaxItersAssignment_1_7_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getConfigAccess().getMaxItersINTTerminalRuleCall_1_7_1_0()); }
		RULE_INT
		{ after(grammarAccess.getConfigAccess().getMaxItersINTTerminalRuleCall_1_7_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_INSTALLATIONS_HEADER : '[' 'Installations' ']';

RULE_INSTALLATION_TYPE : 'Installation';

RULE_MAINTENANCES_HEADER : '[' 'Maintenances' ']';

RULE_MAINTENANCE_TYPE : 'Maintenance';

RULE_OPTIONS_HEADER : '[' 'Options' ']';

RULE_FLOAT : RULE_INT+ '.' RULE_INT+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
