/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.uniovi.dsl.scheduling.scheduling.Config;
import org.uniovi.dsl.scheduling.scheduling.InstallationDef;
import org.uniovi.dsl.scheduling.scheduling.Installations;
import org.uniovi.dsl.scheduling.scheduling.MaintDef;
import org.uniovi.dsl.scheduling.scheduling.Maintenances;
import org.uniovi.dsl.scheduling.scheduling.Program;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

@SuppressWarnings("all")
public class SchedulingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SchedulingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SchedulingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SchedulingPackage.CONFIG:
				sequence_Config(context, (Config) semanticObject); 
				return; 
			case SchedulingPackage.INSTALLATION_DEF:
				sequence_InstallationDef(context, (InstallationDef) semanticObject); 
				return; 
			case SchedulingPackage.INSTALLATIONS:
				sequence_Installations(context, (Installations) semanticObject); 
				return; 
			case SchedulingPackage.MAINT_DEF:
				sequence_MaintDef(context, (MaintDef) semanticObject); 
				return; 
			case SchedulingPackage.MAINTENANCES:
				sequence_Maintenances(context, (Maintenances) semanticObject); 
				return; 
			case SchedulingPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Config returns Config
	 *
	 * Constraint:
	 *     (
	 *         input=STRING | 
	 *         randomState=INT | 
	 *         probBeforeScheduling=FLOAT | 
	 *         rateOfChange=FLOAT | 
	 *         daysPerPeriod=INT | 
	 *         numberOfPeriods=INT | 
	 *         extraHours=INT | 
	 *         maxIters=INT
	 *     )+
	 * </pre>
	 */
	protected void sequence_Config(ISerializationContext context, Config semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InstallationDef returns InstallationDef
	 *
	 * Constraint:
	 *     (id=ID (installationName=STRING | capacity=INT)+)
	 * </pre>
	 */
	protected void sequence_InstallationDef(ISerializationContext context, InstallationDef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Installations returns Installations
	 *
	 * Constraint:
	 *     installations+=InstallationDef+
	 * </pre>
	 */
	protected void sequence_Installations(ISerializationContext context, Installations semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MaintDef returns MaintDef
	 *
	 * Constraint:
	 *     (
	 *         id=ID 
	 *         (
	 *             maintName=STRING | 
	 *             hours=INT | 
	 *             duration=INT | 
	 *             priority=INT | 
	 *             includes=List | 
	 *             installations=List
	 *         )*
	 *     )
	 * </pre>
	 */
	protected void sequence_MaintDef(ISerializationContext context, MaintDef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Maintenances returns Maintenances
	 *
	 * Constraint:
	 *     maints+=MaintDef+
	 * </pre>
	 */
	protected void sequence_Maintenances(ISerializationContext context, Maintenances semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (installations=Installations | maintenances=Maintenances | options=Config)+
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
