/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

@SuppressWarnings("all")
public class SchedulingSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SchedulingGrammarAccess grammarAccess;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SchedulingGrammarAccess) access;
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getINSTALLATIONS_HEADERRule())
			return getINSTALLATIONS_HEADERToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getINSTALLATION_TYPERule())
			return getINSTALLATION_TYPEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getMAINTENANCES_HEADERRule())
			return getMAINTENANCES_HEADERToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getMAINTENANCE_TYPERule())
			return getMAINTENANCE_TYPEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getOPTIONS_HEADERRule())
			return getOPTIONS_HEADERToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal INSTALLATIONS_HEADER: '[' 'Installations' ']';
	 */
	protected String getINSTALLATIONS_HEADERToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[Installations]";
	}
	
	/**
	 * terminal INSTALLATION_TYPE: 'Installation';
	 */
	protected String getINSTALLATION_TYPEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Installation";
	}
	
	/**
	 * terminal MAINTENANCES_HEADER: '[' 'Maintenances' ']';
	 */
	protected String getMAINTENANCES_HEADERToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[Maintenances]";
	}
	
	/**
	 * terminal MAINTENANCE_TYPE: 'Maintenance';
	 */
	protected String getMAINTENANCE_TYPEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Maintenance";
	}
	
	/**
	 * terminal OPTIONS_HEADER: '[' 'Options' ']';
	 */
	protected String getOPTIONS_HEADERToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[Options]";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

}
