/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SchedulingGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.Program");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Assignment cInstallationsAssignment_0 = (Assignment)cUnorderedGroup.eContents().get(0);
		private final RuleCall cInstallationsInstallationsParserRuleCall_0_0 = (RuleCall)cInstallationsAssignment_0.eContents().get(0);
		private final Assignment cMaintenancesAssignment_1 = (Assignment)cUnorderedGroup.eContents().get(1);
		private final RuleCall cMaintenancesMaintenancesParserRuleCall_1_0 = (RuleCall)cMaintenancesAssignment_1.eContents().get(0);
		private final Assignment cOptionsAssignment_2 = (Assignment)cUnorderedGroup.eContents().get(2);
		private final RuleCall cOptionsConfigParserRuleCall_2_0 = (RuleCall)cOptionsAssignment_2.eContents().get(0);
		
		//Program
		//    : installations=Installations & maintenances=Maintenances & options=Config
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//installations=Installations & maintenances=Maintenances & options=Config
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//installations=Installations
		public Assignment getInstallationsAssignment_0() { return cInstallationsAssignment_0; }
		
		//Installations
		public RuleCall getInstallationsInstallationsParserRuleCall_0_0() { return cInstallationsInstallationsParserRuleCall_0_0; }
		
		//maintenances=Maintenances
		public Assignment getMaintenancesAssignment_1() { return cMaintenancesAssignment_1; }
		
		//Maintenances
		public RuleCall getMaintenancesMaintenancesParserRuleCall_1_0() { return cMaintenancesMaintenancesParserRuleCall_1_0; }
		
		//options=Config
		public Assignment getOptionsAssignment_2() { return cOptionsAssignment_2; }
		
		//Config
		public RuleCall getOptionsConfigParserRuleCall_2_0() { return cOptionsConfigParserRuleCall_2_0; }
	}
	public class InstallationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.Installations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINSTALLATIONS_HEADERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cInstallationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInstallationsInstallationDefParserRuleCall_1_0 = (RuleCall)cInstallationsAssignment_1.eContents().get(0);
		
		//Installations
		//    : INSTALLATIONS_HEADER (installations+=InstallationDef)+
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//INSTALLATIONS_HEADER (installations+=InstallationDef)+
		public Group getGroup() { return cGroup; }
		
		//INSTALLATIONS_HEADER
		public RuleCall getINSTALLATIONS_HEADERTerminalRuleCall_0() { return cINSTALLATIONS_HEADERTerminalRuleCall_0; }
		
		//(installations+=InstallationDef)+
		public Assignment getInstallationsAssignment_1() { return cInstallationsAssignment_1; }
		
		//InstallationDef
		public RuleCall getInstallationsInstallationDefParserRuleCall_1_0() { return cInstallationsInstallationDefParserRuleCall_1_0; }
	}
	public class InstallationDefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.InstallationDef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINSTALLATION_TYPETerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cNameKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cInstallationNameAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cInstallationNameSTRINGTerminalRuleCall_2_0_1_0 = (RuleCall)cInstallationNameAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cCapacityKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cCapacityAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cCapacityINTTerminalRuleCall_2_1_1_0 = (RuleCall)cCapacityAssignment_2_1_1.eContents().get(0);
		
		//InstallationDef
		//    : INSTALLATION_TYPE id=ID (
		//        ('Name:' installationName=STRING) &
		//        ('Capacity:' capacity=INT))
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//INSTALLATION_TYPE id=ID (
		//       ('Name:' installationName=STRING) &
		//       ('Capacity:' capacity=INT))
		public Group getGroup() { return cGroup; }
		
		//INSTALLATION_TYPE
		public RuleCall getINSTALLATION_TYPETerminalRuleCall_0() { return cINSTALLATION_TYPETerminalRuleCall_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//(
		//       ('Name:' installationName=STRING) &
		//       ('Capacity:' capacity=INT))
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//('Name:' installationName=STRING)
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'Name:'
		public Keyword getNameKeyword_2_0_0() { return cNameKeyword_2_0_0; }
		
		//installationName=STRING
		public Assignment getInstallationNameAssignment_2_0_1() { return cInstallationNameAssignment_2_0_1; }
		
		//STRING
		public RuleCall getInstallationNameSTRINGTerminalRuleCall_2_0_1_0() { return cInstallationNameSTRINGTerminalRuleCall_2_0_1_0; }
		
		//('Capacity:' capacity=INT)
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'Capacity:'
		public Keyword getCapacityKeyword_2_1_0() { return cCapacityKeyword_2_1_0; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_2_1_1() { return cCapacityAssignment_2_1_1; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_2_1_1_0() { return cCapacityINTTerminalRuleCall_2_1_1_0; }
	}
	public class MaintenancesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.Maintenances");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMAINTENANCES_HEADERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cMaintsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMaintsMaintDefParserRuleCall_1_0 = (RuleCall)cMaintsAssignment_1.eContents().get(0);
		
		//Maintenances
		//    : MAINTENANCES_HEADER (maints+=MaintDef)+
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//MAINTENANCES_HEADER (maints+=MaintDef)+
		public Group getGroup() { return cGroup; }
		
		//MAINTENANCES_HEADER
		public RuleCall getMAINTENANCES_HEADERTerminalRuleCall_0() { return cMAINTENANCES_HEADERTerminalRuleCall_0; }
		
		//(maints+=MaintDef)+
		public Assignment getMaintsAssignment_1() { return cMaintsAssignment_1; }
		
		//MaintDef
		public RuleCall getMaintsMaintDefParserRuleCall_1_0() { return cMaintsMaintDefParserRuleCall_1_0; }
	}
	public class MaintDefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.MaintDef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMAINTENANCE_TYPETerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cNameKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cMaintNameAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cMaintNameSTRINGTerminalRuleCall_2_0_1_0 = (RuleCall)cMaintNameAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cIntervalKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cHoursAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cHoursINTTerminalRuleCall_2_1_1_0 = (RuleCall)cHoursAssignment_2_1_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cPeriodsKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cDurationAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cDurationINTTerminalRuleCall_2_2_1_0 = (RuleCall)cDurationAssignment_2_2_1.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cUnorderedGroup_2.eContents().get(3);
		private final Keyword cPriorityKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cPriorityAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cPriorityINTTerminalRuleCall_2_3_1_0 = (RuleCall)cPriorityAssignment_2_3_1.eContents().get(0);
		private final Group cGroup_2_4 = (Group)cUnorderedGroup_2.eContents().get(4);
		private final Keyword cIncludesKeyword_2_4_0 = (Keyword)cGroup_2_4.eContents().get(0);
		private final Assignment cIncludesAssignment_2_4_1 = (Assignment)cGroup_2_4.eContents().get(1);
		private final RuleCall cIncludesListParserRuleCall_2_4_1_0 = (RuleCall)cIncludesAssignment_2_4_1.eContents().get(0);
		private final Group cGroup_2_5 = (Group)cUnorderedGroup_2.eContents().get(5);
		private final Keyword cInstallationsKeyword_2_5_0 = (Keyword)cGroup_2_5.eContents().get(0);
		private final Assignment cInstallationsAssignment_2_5_1 = (Assignment)cGroup_2_5.eContents().get(1);
		private final RuleCall cInstallationsListParserRuleCall_2_5_1_0 = (RuleCall)cInstallationsAssignment_2_5_1.eContents().get(0);
		
		//MaintDef
		//    : MAINTENANCE_TYPE id=ID (
		//        ('Name:' maintName=STRING) &
		//        ('Interval:' hours=INT) &
		//        ('Periods:' duration=INT) &
		//        ('Priority:' priority=INT)? &
		//        ('Includes:' includes=List)? &
		//        ('Installations:' installations=List))
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//MAINTENANCE_TYPE id=ID (
		//       ('Name:' maintName=STRING) &
		//       ('Interval:' hours=INT) &
		//       ('Periods:' duration=INT) &
		//       ('Priority:' priority=INT)? &
		//       ('Includes:' includes=List)? &
		//       ('Installations:' installations=List))
		public Group getGroup() { return cGroup; }
		
		//MAINTENANCE_TYPE
		public RuleCall getMAINTENANCE_TYPETerminalRuleCall_0() { return cMAINTENANCE_TYPETerminalRuleCall_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//(
		//       ('Name:' maintName=STRING) &
		//       ('Interval:' hours=INT) &
		//       ('Periods:' duration=INT) &
		//       ('Priority:' priority=INT)? &
		//       ('Includes:' includes=List)? &
		//       ('Installations:' installations=List))
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//('Name:' maintName=STRING)
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'Name:'
		public Keyword getNameKeyword_2_0_0() { return cNameKeyword_2_0_0; }
		
		//maintName=STRING
		public Assignment getMaintNameAssignment_2_0_1() { return cMaintNameAssignment_2_0_1; }
		
		//STRING
		public RuleCall getMaintNameSTRINGTerminalRuleCall_2_0_1_0() { return cMaintNameSTRINGTerminalRuleCall_2_0_1_0; }
		
		//('Interval:' hours=INT)
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'Interval:'
		public Keyword getIntervalKeyword_2_1_0() { return cIntervalKeyword_2_1_0; }
		
		//hours=INT
		public Assignment getHoursAssignment_2_1_1() { return cHoursAssignment_2_1_1; }
		
		//INT
		public RuleCall getHoursINTTerminalRuleCall_2_1_1_0() { return cHoursINTTerminalRuleCall_2_1_1_0; }
		
		//('Periods:' duration=INT)
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'Periods:'
		public Keyword getPeriodsKeyword_2_2_0() { return cPeriodsKeyword_2_2_0; }
		
		//duration=INT
		public Assignment getDurationAssignment_2_2_1() { return cDurationAssignment_2_2_1; }
		
		//INT
		public RuleCall getDurationINTTerminalRuleCall_2_2_1_0() { return cDurationINTTerminalRuleCall_2_2_1_0; }
		
		//('Priority:' priority=INT)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'Priority:'
		public Keyword getPriorityKeyword_2_3_0() { return cPriorityKeyword_2_3_0; }
		
		//priority=INT
		public Assignment getPriorityAssignment_2_3_1() { return cPriorityAssignment_2_3_1; }
		
		//INT
		public RuleCall getPriorityINTTerminalRuleCall_2_3_1_0() { return cPriorityINTTerminalRuleCall_2_3_1_0; }
		
		//('Includes:' includes=List)?
		public Group getGroup_2_4() { return cGroup_2_4; }
		
		//'Includes:'
		public Keyword getIncludesKeyword_2_4_0() { return cIncludesKeyword_2_4_0; }
		
		//includes=List
		public Assignment getIncludesAssignment_2_4_1() { return cIncludesAssignment_2_4_1; }
		
		//List
		public RuleCall getIncludesListParserRuleCall_2_4_1_0() { return cIncludesListParserRuleCall_2_4_1_0; }
		
		//('Installations:' installations=List)
		public Group getGroup_2_5() { return cGroup_2_5; }
		
		//'Installations:'
		public Keyword getInstallationsKeyword_2_5_0() { return cInstallationsKeyword_2_5_0; }
		
		//installations=List
		public Assignment getInstallationsAssignment_2_5_1() { return cInstallationsAssignment_2_5_1; }
		
		//List
		public RuleCall getInstallationsListParserRuleCall_2_5_1_0() { return cInstallationsListParserRuleCall_2_5_1_0; }
	}
	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOPTIONS_HEADERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cInputKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cInputAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cInputSTRINGTerminalRuleCall_1_0_1_0 = (RuleCall)cInputAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cRandom_stateKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cRandomStateAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cRandomStateINTTerminalRuleCall_1_1_1_0 = (RuleCall)cRandomStateAssignment_1_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cUnorderedGroup_1.eContents().get(2);
		private final Keyword cProb_before_restrictionKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cProbBeforeSchedulingAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0 = (RuleCall)cProbBeforeSchedulingAssignment_1_2_1.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cUnorderedGroup_1.eContents().get(3);
		private final Keyword cRate_of_changeKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cRateOfChangeAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cRateOfChangeFLOATTerminalRuleCall_1_3_1_0 = (RuleCall)cRateOfChangeAssignment_1_3_1.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cUnorderedGroup_1.eContents().get(4);
		private final Keyword cDays_per_periodKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Assignment cDaysPerPeriodAssignment_1_4_1 = (Assignment)cGroup_1_4.eContents().get(1);
		private final RuleCall cDaysPerPeriodINTTerminalRuleCall_1_4_1_0 = (RuleCall)cDaysPerPeriodAssignment_1_4_1.eContents().get(0);
		private final Group cGroup_1_5 = (Group)cUnorderedGroup_1.eContents().get(5);
		private final Keyword cNumber_of_periodsKeyword_1_5_0 = (Keyword)cGroup_1_5.eContents().get(0);
		private final Assignment cNumberOfPeriodsAssignment_1_5_1 = (Assignment)cGroup_1_5.eContents().get(1);
		private final RuleCall cNumberOfPeriodsINTTerminalRuleCall_1_5_1_0 = (RuleCall)cNumberOfPeriodsAssignment_1_5_1.eContents().get(0);
		private final Group cGroup_1_6 = (Group)cUnorderedGroup_1.eContents().get(6);
		private final Keyword cExtra_hoursKeyword_1_6_0 = (Keyword)cGroup_1_6.eContents().get(0);
		private final Assignment cExtraHoursAssignment_1_6_1 = (Assignment)cGroup_1_6.eContents().get(1);
		private final RuleCall cExtraHoursINTTerminalRuleCall_1_6_1_0 = (RuleCall)cExtraHoursAssignment_1_6_1.eContents().get(0);
		private final Group cGroup_1_7 = (Group)cUnorderedGroup_1.eContents().get(7);
		private final Keyword cIterationsKeyword_1_7_0 = (Keyword)cGroup_1_7.eContents().get(0);
		private final Assignment cMaxItersAssignment_1_7_1 = (Assignment)cGroup_1_7.eContents().get(1);
		private final RuleCall cMaxItersINTTerminalRuleCall_1_7_1_0 = (RuleCall)cMaxItersAssignment_1_7_1.eContents().get(0);
		
		//Config
		//    : OPTIONS_HEADER (
		//        ('Input:' input=STRING) &
		//        ('Random_state:' randomState=INT)? &
		//        ('Prob_before_restriction:' probBeforeScheduling=FLOAT)? &
		//        ('Rate_of_change:' rateOfChange=FLOAT)? &
		//        ('Days_per_period:' daysPerPeriod=INT)? &
		//        ('Number_of_periods:' numberOfPeriods=INT)? &
		//        ('Extra_hours:' extraHours=INT)? &
		//        ('Iterations:' maxIters=INT)? )
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//OPTIONS_HEADER (
		//       ('Input:' input=STRING) &
		//       ('Random_state:' randomState=INT)? &
		//       ('Prob_before_restriction:' probBeforeScheduling=FLOAT)? &
		//       ('Rate_of_change:' rateOfChange=FLOAT)? &
		//       ('Days_per_period:' daysPerPeriod=INT)? &
		//       ('Number_of_periods:' numberOfPeriods=INT)? &
		//       ('Extra_hours:' extraHours=INT)? &
		//       ('Iterations:' maxIters=INT)? )
		public Group getGroup() { return cGroup; }
		
		//OPTIONS_HEADER
		public RuleCall getOPTIONS_HEADERTerminalRuleCall_0() { return cOPTIONS_HEADERTerminalRuleCall_0; }
		
		//(
		//       ('Input:' input=STRING) &
		//       ('Random_state:' randomState=INT)? &
		//       ('Prob_before_restriction:' probBeforeScheduling=FLOAT)? &
		//       ('Rate_of_change:' rateOfChange=FLOAT)? &
		//       ('Days_per_period:' daysPerPeriod=INT)? &
		//       ('Number_of_periods:' numberOfPeriods=INT)? &
		//       ('Extra_hours:' extraHours=INT)? &
		//       ('Iterations:' maxIters=INT)? )
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//('Input:' input=STRING)
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'Input:'
		public Keyword getInputKeyword_1_0_0() { return cInputKeyword_1_0_0; }
		
		//input=STRING
		public Assignment getInputAssignment_1_0_1() { return cInputAssignment_1_0_1; }
		
		//STRING
		public RuleCall getInputSTRINGTerminalRuleCall_1_0_1_0() { return cInputSTRINGTerminalRuleCall_1_0_1_0; }
		
		//('Random_state:' randomState=INT)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'Random_state:'
		public Keyword getRandom_stateKeyword_1_1_0() { return cRandom_stateKeyword_1_1_0; }
		
		//randomState=INT
		public Assignment getRandomStateAssignment_1_1_1() { return cRandomStateAssignment_1_1_1; }
		
		//INT
		public RuleCall getRandomStateINTTerminalRuleCall_1_1_1_0() { return cRandomStateINTTerminalRuleCall_1_1_1_0; }
		
		//('Prob_before_restriction:' probBeforeScheduling=FLOAT)?
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//'Prob_before_restriction:'
		public Keyword getProb_before_restrictionKeyword_1_2_0() { return cProb_before_restrictionKeyword_1_2_0; }
		
		//probBeforeScheduling=FLOAT
		public Assignment getProbBeforeSchedulingAssignment_1_2_1() { return cProbBeforeSchedulingAssignment_1_2_1; }
		
		//FLOAT
		public RuleCall getProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0() { return cProbBeforeSchedulingFLOATTerminalRuleCall_1_2_1_0; }
		
		//('Rate_of_change:' rateOfChange=FLOAT)?
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//'Rate_of_change:'
		public Keyword getRate_of_changeKeyword_1_3_0() { return cRate_of_changeKeyword_1_3_0; }
		
		//rateOfChange=FLOAT
		public Assignment getRateOfChangeAssignment_1_3_1() { return cRateOfChangeAssignment_1_3_1; }
		
		//FLOAT
		public RuleCall getRateOfChangeFLOATTerminalRuleCall_1_3_1_0() { return cRateOfChangeFLOATTerminalRuleCall_1_3_1_0; }
		
		//('Days_per_period:' daysPerPeriod=INT)?
		public Group getGroup_1_4() { return cGroup_1_4; }
		
		//'Days_per_period:'
		public Keyword getDays_per_periodKeyword_1_4_0() { return cDays_per_periodKeyword_1_4_0; }
		
		//daysPerPeriod=INT
		public Assignment getDaysPerPeriodAssignment_1_4_1() { return cDaysPerPeriodAssignment_1_4_1; }
		
		//INT
		public RuleCall getDaysPerPeriodINTTerminalRuleCall_1_4_1_0() { return cDaysPerPeriodINTTerminalRuleCall_1_4_1_0; }
		
		//('Number_of_periods:' numberOfPeriods=INT)?
		public Group getGroup_1_5() { return cGroup_1_5; }
		
		//'Number_of_periods:'
		public Keyword getNumber_of_periodsKeyword_1_5_0() { return cNumber_of_periodsKeyword_1_5_0; }
		
		//numberOfPeriods=INT
		public Assignment getNumberOfPeriodsAssignment_1_5_1() { return cNumberOfPeriodsAssignment_1_5_1; }
		
		//INT
		public RuleCall getNumberOfPeriodsINTTerminalRuleCall_1_5_1_0() { return cNumberOfPeriodsINTTerminalRuleCall_1_5_1_0; }
		
		//('Extra_hours:' extraHours=INT)?
		public Group getGroup_1_6() { return cGroup_1_6; }
		
		//'Extra_hours:'
		public Keyword getExtra_hoursKeyword_1_6_0() { return cExtra_hoursKeyword_1_6_0; }
		
		//extraHours=INT
		public Assignment getExtraHoursAssignment_1_6_1() { return cExtraHoursAssignment_1_6_1; }
		
		//INT
		public RuleCall getExtraHoursINTTerminalRuleCall_1_6_1_0() { return cExtraHoursINTTerminalRuleCall_1_6_1_0; }
		
		//('Iterations:' maxIters=INT)?
		public Group getGroup_1_7() { return cGroup_1_7; }
		
		//'Iterations:'
		public Keyword getIterationsKeyword_1_7_0() { return cIterationsKeyword_1_7_0; }
		
		//maxIters=INT
		public Assignment getMaxItersAssignment_1_7_1() { return cMaxItersAssignment_1_7_1; }
		
		//INT
		public RuleCall getMaxItersINTTerminalRuleCall_1_7_1_0() { return cMaxItersINTTerminalRuleCall_1_7_1_0; }
	}
	public class ListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.List");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//List
		//    : ID (',' ID)*
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//ID (',' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//(',' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final ProgramElements pProgram;
	private final InstallationsElements pInstallations;
	private final TerminalRule tINSTALLATIONS_HEADER;
	private final InstallationDefElements pInstallationDef;
	private final TerminalRule tINSTALLATION_TYPE;
	private final MaintenancesElements pMaintenances;
	private final TerminalRule tMAINTENANCES_HEADER;
	private final MaintDefElements pMaintDef;
	private final TerminalRule tMAINTENANCE_TYPE;
	private final ConfigElements pConfig;
	private final TerminalRule tOPTIONS_HEADER;
	private final ListElements pList;
	private final TerminalRule tFLOAT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SchedulingGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pInstallations = new InstallationsElements();
		this.tINSTALLATIONS_HEADER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.INSTALLATIONS_HEADER");
		this.pInstallationDef = new InstallationDefElements();
		this.tINSTALLATION_TYPE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.INSTALLATION_TYPE");
		this.pMaintenances = new MaintenancesElements();
		this.tMAINTENANCES_HEADER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.MAINTENANCES_HEADER");
		this.pMaintDef = new MaintDefElements();
		this.tMAINTENANCE_TYPE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.MAINTENANCE_TYPE");
		this.pConfig = new ConfigElements();
		this.tOPTIONS_HEADER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.OPTIONS_HEADER");
		this.pList = new ListElements();
		this.tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.uniovi.dsl.scheduling.Scheduling.FLOAT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.uniovi.dsl.scheduling.Scheduling".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program
	//    : installations=Installations & maintenances=Maintenances & options=Config
	//    ;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Installations
	//    : INSTALLATIONS_HEADER (installations+=InstallationDef)+
	//    ;
	public InstallationsElements getInstallationsAccess() {
		return pInstallations;
	}
	
	public ParserRule getInstallationsRule() {
		return getInstallationsAccess().getRule();
	}
	
	//terminal INSTALLATIONS_HEADER: '[' 'Installations' ']';
	public TerminalRule getINSTALLATIONS_HEADERRule() {
		return tINSTALLATIONS_HEADER;
	}
	
	//InstallationDef
	//    : INSTALLATION_TYPE id=ID (
	//        ('Name:' installationName=STRING) &
	//        ('Capacity:' capacity=INT))
	//    ;
	public InstallationDefElements getInstallationDefAccess() {
		return pInstallationDef;
	}
	
	public ParserRule getInstallationDefRule() {
		return getInstallationDefAccess().getRule();
	}
	
	//terminal INSTALLATION_TYPE: 'Installation';
	public TerminalRule getINSTALLATION_TYPERule() {
		return tINSTALLATION_TYPE;
	}
	
	//Maintenances
	//    : MAINTENANCES_HEADER (maints+=MaintDef)+
	//    ;
	public MaintenancesElements getMaintenancesAccess() {
		return pMaintenances;
	}
	
	public ParserRule getMaintenancesRule() {
		return getMaintenancesAccess().getRule();
	}
	
	//terminal MAINTENANCES_HEADER: '[' 'Maintenances' ']';
	public TerminalRule getMAINTENANCES_HEADERRule() {
		return tMAINTENANCES_HEADER;
	}
	
	//MaintDef
	//    : MAINTENANCE_TYPE id=ID (
	//        ('Name:' maintName=STRING) &
	//        ('Interval:' hours=INT) &
	//        ('Periods:' duration=INT) &
	//        ('Priority:' priority=INT)? &
	//        ('Includes:' includes=List)? &
	//        ('Installations:' installations=List))
	//    ;
	public MaintDefElements getMaintDefAccess() {
		return pMaintDef;
	}
	
	public ParserRule getMaintDefRule() {
		return getMaintDefAccess().getRule();
	}
	
	//terminal MAINTENANCE_TYPE: 'Maintenance';
	public TerminalRule getMAINTENANCE_TYPERule() {
		return tMAINTENANCE_TYPE;
	}
	
	//Config
	//    : OPTIONS_HEADER (
	//        ('Input:' input=STRING) &
	//        ('Random_state:' randomState=INT)? &
	//        ('Prob_before_restriction:' probBeforeScheduling=FLOAT)? &
	//        ('Rate_of_change:' rateOfChange=FLOAT)? &
	//        ('Days_per_period:' daysPerPeriod=INT)? &
	//        ('Number_of_periods:' numberOfPeriods=INT)? &
	//        ('Extra_hours:' extraHours=INT)? &
	//        ('Iterations:' maxIters=INT)? )
	//    ;
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}
	
	//terminal OPTIONS_HEADER: '[' 'Options' ']';
	public TerminalRule getOPTIONS_HEADERRule() {
		return tOPTIONS_HEADER;
	}
	
	//List
	//    : ID (',' ID)*
	//    ;
	public ListElements getListAccess() {
		return pList;
	}
	
	public ParserRule getListRule() {
		return getListAccess().getRule();
	}
	
	//terminal FLOAT
	//    : (INT)+'.'(INT)+
	//    ;
	public TerminalRule getFLOATRule() {
		return tFLOAT;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
