/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SchedulingWebModule extends AbstractSchedulingWebModule {
}
