/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSchedulingValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.uniovi.dsl.scheduling.scheduling.SchedulingPackage.eINSTANCE);
		return result;
	}
}
