/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.uniovi.dsl.scheduling.SchedulingRuntimeModule;
import org.uniovi.dsl.scheduling.SchedulingStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SchedulingIdeSetup extends SchedulingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SchedulingRuntimeModule(), new SchedulingIdeModule()));
	}
	
}
