/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSchedulingScopeProvider extends DelegatingScopeProvider {
}
