/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.uniovi.dsl.scheduling.ide.contentassist.antlr.internal.InternalSchedulingParser;
import org.uniovi.dsl.scheduling.services.SchedulingGrammarAccess;

public class SchedulingParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SchedulingGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SchedulingGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstallationsAccess().getGroup(), "rule__Installations__Group__0");
			builder.put(grammarAccess.getInstallationDefAccess().getGroup(), "rule__InstallationDef__Group__0");
			builder.put(grammarAccess.getInstallationDefAccess().getGroup_2_0(), "rule__InstallationDef__Group_2_0__0");
			builder.put(grammarAccess.getInstallationDefAccess().getGroup_2_1(), "rule__InstallationDef__Group_2_1__0");
			builder.put(grammarAccess.getMaintenancesAccess().getGroup(), "rule__Maintenances__Group__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup(), "rule__MaintDef__Group__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_0(), "rule__MaintDef__Group_2_0__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_1(), "rule__MaintDef__Group_2_1__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_2(), "rule__MaintDef__Group_2_2__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_3(), "rule__MaintDef__Group_2_3__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_4(), "rule__MaintDef__Group_2_4__0");
			builder.put(grammarAccess.getMaintDefAccess().getGroup_2_5(), "rule__MaintDef__Group_2_5__0");
			builder.put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_0(), "rule__Config__Group_1_0__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_1(), "rule__Config__Group_1_1__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_2(), "rule__Config__Group_1_2__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_3(), "rule__Config__Group_1_3__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_4(), "rule__Config__Group_1_4__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_5(), "rule__Config__Group_1_5__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_6(), "rule__Config__Group_1_6__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_1_7(), "rule__Config__Group_1_7__0");
			builder.put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
			builder.put(grammarAccess.getListAccess().getGroup_1(), "rule__List__Group_1__0");
			builder.put(grammarAccess.getProgramAccess().getInstallationsAssignment_0(), "rule__Program__InstallationsAssignment_0");
			builder.put(grammarAccess.getProgramAccess().getMaintenancesAssignment_1(), "rule__Program__MaintenancesAssignment_1");
			builder.put(grammarAccess.getProgramAccess().getOptionsAssignment_2(), "rule__Program__OptionsAssignment_2");
			builder.put(grammarAccess.getInstallationsAccess().getInstallationsAssignment_1(), "rule__Installations__InstallationsAssignment_1");
			builder.put(grammarAccess.getInstallationDefAccess().getIdAssignment_1(), "rule__InstallationDef__IdAssignment_1");
			builder.put(grammarAccess.getInstallationDefAccess().getInstallationNameAssignment_2_0_1(), "rule__InstallationDef__InstallationNameAssignment_2_0_1");
			builder.put(grammarAccess.getInstallationDefAccess().getCapacityAssignment_2_1_1(), "rule__InstallationDef__CapacityAssignment_2_1_1");
			builder.put(grammarAccess.getMaintenancesAccess().getMaintsAssignment_1(), "rule__Maintenances__MaintsAssignment_1");
			builder.put(grammarAccess.getMaintDefAccess().getIdAssignment_1(), "rule__MaintDef__IdAssignment_1");
			builder.put(grammarAccess.getMaintDefAccess().getMaintNameAssignment_2_0_1(), "rule__MaintDef__MaintNameAssignment_2_0_1");
			builder.put(grammarAccess.getMaintDefAccess().getHoursAssignment_2_1_1(), "rule__MaintDef__HoursAssignment_2_1_1");
			builder.put(grammarAccess.getMaintDefAccess().getDurationAssignment_2_2_1(), "rule__MaintDef__DurationAssignment_2_2_1");
			builder.put(grammarAccess.getMaintDefAccess().getPriorityAssignment_2_3_1(), "rule__MaintDef__PriorityAssignment_2_3_1");
			builder.put(grammarAccess.getMaintDefAccess().getIncludesAssignment_2_4_1(), "rule__MaintDef__IncludesAssignment_2_4_1");
			builder.put(grammarAccess.getMaintDefAccess().getInstallationsAssignment_2_5_1(), "rule__MaintDef__InstallationsAssignment_2_5_1");
			builder.put(grammarAccess.getConfigAccess().getInputAssignment_1_0_1(), "rule__Config__InputAssignment_1_0_1");
			builder.put(grammarAccess.getConfigAccess().getRandomStateAssignment_1_1_1(), "rule__Config__RandomStateAssignment_1_1_1");
			builder.put(grammarAccess.getConfigAccess().getProbBeforeSchedulingAssignment_1_2_1(), "rule__Config__ProbBeforeSchedulingAssignment_1_2_1");
			builder.put(grammarAccess.getConfigAccess().getRateOfChangeAssignment_1_3_1(), "rule__Config__RateOfChangeAssignment_1_3_1");
			builder.put(grammarAccess.getConfigAccess().getDaysPerPeriodAssignment_1_4_1(), "rule__Config__DaysPerPeriodAssignment_1_4_1");
			builder.put(grammarAccess.getConfigAccess().getNumberOfPeriodsAssignment_1_5_1(), "rule__Config__NumberOfPeriodsAssignment_1_5_1");
			builder.put(grammarAccess.getConfigAccess().getExtraHoursAssignment_1_6_1(), "rule__Config__ExtraHoursAssignment_1_6_1");
			builder.put(grammarAccess.getConfigAccess().getMaxItersAssignment_1_7_1(), "rule__Config__MaxItersAssignment_1_7_1");
			builder.put(grammarAccess.getProgramAccess().getUnorderedGroup(), "rule__Program__UnorderedGroup");
			builder.put(grammarAccess.getInstallationDefAccess().getUnorderedGroup_2(), "rule__InstallationDef__UnorderedGroup_2");
			builder.put(grammarAccess.getMaintDefAccess().getUnorderedGroup_2(), "rule__MaintDef__UnorderedGroup_2");
			builder.put(grammarAccess.getConfigAccess().getUnorderedGroup_1(), "rule__Config__UnorderedGroup_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SchedulingGrammarAccess grammarAccess;

	@Override
	protected InternalSchedulingParser createParser() {
		InternalSchedulingParser result = new InternalSchedulingParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SchedulingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchedulingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
