/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ide;


/**
 * Use this class to register ide components.
 */
public class SchedulingIdeModule extends AbstractSchedulingIdeModule {
}
