/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.uniovi.dsl.scheduling.ui.internal.SchedulingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SchedulingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SchedulingActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SchedulingActivator activator = SchedulingActivator.getInstance();
		return activator != null ? activator.getInjector(SchedulingActivator.ORG_UNIOVI_DSL_SCHEDULING_SCHEDULING) : null;
	}

}
