/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.uniovi.dsl.scheduling.scheduling.Config;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Config</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getInput <em>Input</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getRandomState <em>Random State</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getProbBeforeScheduling <em>Prob Before Scheduling</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getRateOfChange <em>Rate Of Change</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getDaysPerPeriod <em>Days Per Period</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getNumberOfPeriods <em>Number Of Periods</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getExtraHours <em>Extra Hours</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ConfigImpl#getMaxIters <em>Max Iters</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConfigImpl extends MinimalEObjectImpl.Container implements Config
{
  /**
   * The default value of the '{@link #getInput() <em>Input</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInput()
   * @generated
   * @ordered
   */
  protected static final String INPUT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInput() <em>Input</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInput()
   * @generated
   * @ordered
   */
  protected String input = INPUT_EDEFAULT;

  /**
   * The default value of the '{@link #getRandomState() <em>Random State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRandomState()
   * @generated
   * @ordered
   */
  protected static final int RANDOM_STATE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRandomState() <em>Random State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRandomState()
   * @generated
   * @ordered
   */
  protected int randomState = RANDOM_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getProbBeforeScheduling() <em>Prob Before Scheduling</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProbBeforeScheduling()
   * @generated
   * @ordered
   */
  protected static final String PROB_BEFORE_SCHEDULING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProbBeforeScheduling() <em>Prob Before Scheduling</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProbBeforeScheduling()
   * @generated
   * @ordered
   */
  protected String probBeforeScheduling = PROB_BEFORE_SCHEDULING_EDEFAULT;

  /**
   * The default value of the '{@link #getRateOfChange() <em>Rate Of Change</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRateOfChange()
   * @generated
   * @ordered
   */
  protected static final String RATE_OF_CHANGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRateOfChange() <em>Rate Of Change</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRateOfChange()
   * @generated
   * @ordered
   */
  protected String rateOfChange = RATE_OF_CHANGE_EDEFAULT;

  /**
   * The default value of the '{@link #getDaysPerPeriod() <em>Days Per Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDaysPerPeriod()
   * @generated
   * @ordered
   */
  protected static final int DAYS_PER_PERIOD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDaysPerPeriod() <em>Days Per Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDaysPerPeriod()
   * @generated
   * @ordered
   */
  protected int daysPerPeriod = DAYS_PER_PERIOD_EDEFAULT;

  /**
   * The default value of the '{@link #getNumberOfPeriods() <em>Number Of Periods</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfPeriods()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_OF_PERIODS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumberOfPeriods() <em>Number Of Periods</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfPeriods()
   * @generated
   * @ordered
   */
  protected int numberOfPeriods = NUMBER_OF_PERIODS_EDEFAULT;

  /**
   * The default value of the '{@link #getExtraHours() <em>Extra Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtraHours()
   * @generated
   * @ordered
   */
  protected static final int EXTRA_HOURS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getExtraHours() <em>Extra Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtraHours()
   * @generated
   * @ordered
   */
  protected int extraHours = EXTRA_HOURS_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxIters() <em>Max Iters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxIters()
   * @generated
   * @ordered
   */
  protected static final int MAX_ITERS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxIters() <em>Max Iters</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxIters()
   * @generated
   * @ordered
   */
  protected int maxIters = MAX_ITERS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchedulingPackage.Literals.CONFIG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInput()
  {
    return input;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInput(String newInput)
  {
    String oldInput = input;
    input = newInput;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__INPUT, oldInput, input));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRandomState()
  {
    return randomState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRandomState(int newRandomState)
  {
    int oldRandomState = randomState;
    randomState = newRandomState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__RANDOM_STATE, oldRandomState, randomState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getProbBeforeScheduling()
  {
    return probBeforeScheduling;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProbBeforeScheduling(String newProbBeforeScheduling)
  {
    String oldProbBeforeScheduling = probBeforeScheduling;
    probBeforeScheduling = newProbBeforeScheduling;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__PROB_BEFORE_SCHEDULING, oldProbBeforeScheduling, probBeforeScheduling));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRateOfChange()
  {
    return rateOfChange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRateOfChange(String newRateOfChange)
  {
    String oldRateOfChange = rateOfChange;
    rateOfChange = newRateOfChange;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__RATE_OF_CHANGE, oldRateOfChange, rateOfChange));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDaysPerPeriod()
  {
    return daysPerPeriod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDaysPerPeriod(int newDaysPerPeriod)
  {
    int oldDaysPerPeriod = daysPerPeriod;
    daysPerPeriod = newDaysPerPeriod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__DAYS_PER_PERIOD, oldDaysPerPeriod, daysPerPeriod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumberOfPeriods()
  {
    return numberOfPeriods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumberOfPeriods(int newNumberOfPeriods)
  {
    int oldNumberOfPeriods = numberOfPeriods;
    numberOfPeriods = newNumberOfPeriods;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__NUMBER_OF_PERIODS, oldNumberOfPeriods, numberOfPeriods));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getExtraHours()
  {
    return extraHours;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExtraHours(int newExtraHours)
  {
    int oldExtraHours = extraHours;
    extraHours = newExtraHours;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__EXTRA_HOURS, oldExtraHours, extraHours));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxIters()
  {
    return maxIters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxIters(int newMaxIters)
  {
    int oldMaxIters = maxIters;
    maxIters = newMaxIters;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.CONFIG__MAX_ITERS, oldMaxIters, maxIters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchedulingPackage.CONFIG__INPUT:
        return getInput();
      case SchedulingPackage.CONFIG__RANDOM_STATE:
        return getRandomState();
      case SchedulingPackage.CONFIG__PROB_BEFORE_SCHEDULING:
        return getProbBeforeScheduling();
      case SchedulingPackage.CONFIG__RATE_OF_CHANGE:
        return getRateOfChange();
      case SchedulingPackage.CONFIG__DAYS_PER_PERIOD:
        return getDaysPerPeriod();
      case SchedulingPackage.CONFIG__NUMBER_OF_PERIODS:
        return getNumberOfPeriods();
      case SchedulingPackage.CONFIG__EXTRA_HOURS:
        return getExtraHours();
      case SchedulingPackage.CONFIG__MAX_ITERS:
        return getMaxIters();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchedulingPackage.CONFIG__INPUT:
        setInput((String)newValue);
        return;
      case SchedulingPackage.CONFIG__RANDOM_STATE:
        setRandomState((Integer)newValue);
        return;
      case SchedulingPackage.CONFIG__PROB_BEFORE_SCHEDULING:
        setProbBeforeScheduling((String)newValue);
        return;
      case SchedulingPackage.CONFIG__RATE_OF_CHANGE:
        setRateOfChange((String)newValue);
        return;
      case SchedulingPackage.CONFIG__DAYS_PER_PERIOD:
        setDaysPerPeriod((Integer)newValue);
        return;
      case SchedulingPackage.CONFIG__NUMBER_OF_PERIODS:
        setNumberOfPeriods((Integer)newValue);
        return;
      case SchedulingPackage.CONFIG__EXTRA_HOURS:
        setExtraHours((Integer)newValue);
        return;
      case SchedulingPackage.CONFIG__MAX_ITERS:
        setMaxIters((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.CONFIG__INPUT:
        setInput(INPUT_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__RANDOM_STATE:
        setRandomState(RANDOM_STATE_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__PROB_BEFORE_SCHEDULING:
        setProbBeforeScheduling(PROB_BEFORE_SCHEDULING_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__RATE_OF_CHANGE:
        setRateOfChange(RATE_OF_CHANGE_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__DAYS_PER_PERIOD:
        setDaysPerPeriod(DAYS_PER_PERIOD_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__NUMBER_OF_PERIODS:
        setNumberOfPeriods(NUMBER_OF_PERIODS_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__EXTRA_HOURS:
        setExtraHours(EXTRA_HOURS_EDEFAULT);
        return;
      case SchedulingPackage.CONFIG__MAX_ITERS:
        setMaxIters(MAX_ITERS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.CONFIG__INPUT:
        return INPUT_EDEFAULT == null ? input != null : !INPUT_EDEFAULT.equals(input);
      case SchedulingPackage.CONFIG__RANDOM_STATE:
        return randomState != RANDOM_STATE_EDEFAULT;
      case SchedulingPackage.CONFIG__PROB_BEFORE_SCHEDULING:
        return PROB_BEFORE_SCHEDULING_EDEFAULT == null ? probBeforeScheduling != null : !PROB_BEFORE_SCHEDULING_EDEFAULT.equals(probBeforeScheduling);
      case SchedulingPackage.CONFIG__RATE_OF_CHANGE:
        return RATE_OF_CHANGE_EDEFAULT == null ? rateOfChange != null : !RATE_OF_CHANGE_EDEFAULT.equals(rateOfChange);
      case SchedulingPackage.CONFIG__DAYS_PER_PERIOD:
        return daysPerPeriod != DAYS_PER_PERIOD_EDEFAULT;
      case SchedulingPackage.CONFIG__NUMBER_OF_PERIODS:
        return numberOfPeriods != NUMBER_OF_PERIODS_EDEFAULT;
      case SchedulingPackage.CONFIG__EXTRA_HOURS:
        return extraHours != EXTRA_HOURS_EDEFAULT;
      case SchedulingPackage.CONFIG__MAX_ITERS:
        return maxIters != MAX_ITERS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (input: ");
    result.append(input);
    result.append(", randomState: ");
    result.append(randomState);
    result.append(", probBeforeScheduling: ");
    result.append(probBeforeScheduling);
    result.append(", rateOfChange: ");
    result.append(rateOfChange);
    result.append(", daysPerPeriod: ");
    result.append(daysPerPeriod);
    result.append(", numberOfPeriods: ");
    result.append(numberOfPeriods);
    result.append(", extraHours: ");
    result.append(extraHours);
    result.append(", maxIters: ");
    result.append(maxIters);
    result.append(')');
    return result.toString();
  }

} //ConfigImpl
