/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.uniovi.dsl.scheduling.scheduling.MaintDef;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Maint Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getMaintName <em>Maint Name</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getHours <em>Hours</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getIncludes <em>Includes</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.MaintDefImpl#getInstallations <em>Installations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MaintDefImpl extends MinimalEObjectImpl.Container implements MaintDef
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getMaintName() <em>Maint Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaintName()
   * @generated
   * @ordered
   */
  protected static final String MAINT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMaintName() <em>Maint Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaintName()
   * @generated
   * @ordered
   */
  protected String maintName = MAINT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getHours() <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHours()
   * @generated
   * @ordered
   */
  protected static final int HOURS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHours() <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHours()
   * @generated
   * @ordered
   */
  protected int hours = HOURS_EDEFAULT;

  /**
   * The default value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected static final int DURATION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected int duration = DURATION_EDEFAULT;

  /**
   * The default value of the '{@link #getPriority() <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPriority()
   * @generated
   * @ordered
   */
  protected static final int PRIORITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPriority() <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPriority()
   * @generated
   * @ordered
   */
  protected int priority = PRIORITY_EDEFAULT;

  /**
   * The default value of the '{@link #getIncludes() <em>Includes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludes()
   * @generated
   * @ordered
   */
  protected static final String INCLUDES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIncludes() <em>Includes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludes()
   * @generated
   * @ordered
   */
  protected String includes = INCLUDES_EDEFAULT;

  /**
   * The default value of the '{@link #getInstallations() <em>Installations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstallations()
   * @generated
   * @ordered
   */
  protected static final String INSTALLATIONS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInstallations() <em>Installations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstallations()
   * @generated
   * @ordered
   */
  protected String installations = INSTALLATIONS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaintDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchedulingPackage.Literals.MAINT_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMaintName()
  {
    return maintName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaintName(String newMaintName)
  {
    String oldMaintName = maintName;
    maintName = newMaintName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__MAINT_NAME, oldMaintName, maintName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getHours()
  {
    return hours;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHours(int newHours)
  {
    int oldHours = hours;
    hours = newHours;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__HOURS, oldHours, hours));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDuration(int newDuration)
  {
    int oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__DURATION, oldDuration, duration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPriority()
  {
    return priority;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPriority(int newPriority)
  {
    int oldPriority = priority;
    priority = newPriority;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__PRIORITY, oldPriority, priority));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIncludes()
  {
    return includes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIncludes(String newIncludes)
  {
    String oldIncludes = includes;
    includes = newIncludes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__INCLUDES, oldIncludes, includes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInstallations()
  {
    return installations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstallations(String newInstallations)
  {
    String oldInstallations = installations;
    installations = newInstallations;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.MAINT_DEF__INSTALLATIONS, oldInstallations, installations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchedulingPackage.MAINT_DEF__ID:
        return getId();
      case SchedulingPackage.MAINT_DEF__MAINT_NAME:
        return getMaintName();
      case SchedulingPackage.MAINT_DEF__HOURS:
        return getHours();
      case SchedulingPackage.MAINT_DEF__DURATION:
        return getDuration();
      case SchedulingPackage.MAINT_DEF__PRIORITY:
        return getPriority();
      case SchedulingPackage.MAINT_DEF__INCLUDES:
        return getIncludes();
      case SchedulingPackage.MAINT_DEF__INSTALLATIONS:
        return getInstallations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchedulingPackage.MAINT_DEF__ID:
        setId((String)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__MAINT_NAME:
        setMaintName((String)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__HOURS:
        setHours((Integer)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__DURATION:
        setDuration((Integer)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__PRIORITY:
        setPriority((Integer)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__INCLUDES:
        setIncludes((String)newValue);
        return;
      case SchedulingPackage.MAINT_DEF__INSTALLATIONS:
        setInstallations((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.MAINT_DEF__ID:
        setId(ID_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__MAINT_NAME:
        setMaintName(MAINT_NAME_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__HOURS:
        setHours(HOURS_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__DURATION:
        setDuration(DURATION_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__PRIORITY:
        setPriority(PRIORITY_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__INCLUDES:
        setIncludes(INCLUDES_EDEFAULT);
        return;
      case SchedulingPackage.MAINT_DEF__INSTALLATIONS:
        setInstallations(INSTALLATIONS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.MAINT_DEF__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case SchedulingPackage.MAINT_DEF__MAINT_NAME:
        return MAINT_NAME_EDEFAULT == null ? maintName != null : !MAINT_NAME_EDEFAULT.equals(maintName);
      case SchedulingPackage.MAINT_DEF__HOURS:
        return hours != HOURS_EDEFAULT;
      case SchedulingPackage.MAINT_DEF__DURATION:
        return duration != DURATION_EDEFAULT;
      case SchedulingPackage.MAINT_DEF__PRIORITY:
        return priority != PRIORITY_EDEFAULT;
      case SchedulingPackage.MAINT_DEF__INCLUDES:
        return INCLUDES_EDEFAULT == null ? includes != null : !INCLUDES_EDEFAULT.equals(includes);
      case SchedulingPackage.MAINT_DEF__INSTALLATIONS:
        return INSTALLATIONS_EDEFAULT == null ? installations != null : !INSTALLATIONS_EDEFAULT.equals(installations);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", maintName: ");
    result.append(maintName);
    result.append(", hours: ");
    result.append(hours);
    result.append(", duration: ");
    result.append(duration);
    result.append(", priority: ");
    result.append(priority);
    result.append(", includes: ");
    result.append(includes);
    result.append(", installations: ");
    result.append(installations);
    result.append(')');
    return result.toString();
  }

} //MaintDefImpl
