/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Installations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Installations#getInstallations <em>Installations</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallations()
 * @model
 * @generated
 */
public interface Installations extends EObject
{
  /**
   * Returns the value of the '<em><b>Installations</b></em>' containment reference list.
   * The list contents are of type {@link org.uniovi.dsl.scheduling.scheduling.InstallationDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Installations</em>' containment reference list.
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getInstallations_Installations()
   * @model containment="true"
   * @generated
   */
  EList<InstallationDef> getInstallations();

} // Installations
