/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Program#getInstallations <em>Installations</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Program#getMaintenances <em>Maintenances</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.Program#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Installations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Installations</em>' containment reference.
   * @see #setInstallations(Installations)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getProgram_Installations()
   * @model containment="true"
   * @generated
   */
  Installations getInstallations();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Program#getInstallations <em>Installations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Installations</em>' containment reference.
   * @see #getInstallations()
   * @generated
   */
  void setInstallations(Installations value);

  /**
   * Returns the value of the '<em><b>Maintenances</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maintenances</em>' containment reference.
   * @see #setMaintenances(Maintenances)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getProgram_Maintenances()
   * @model containment="true"
   * @generated
   */
  Maintenances getMaintenances();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Program#getMaintenances <em>Maintenances</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maintenances</em>' containment reference.
   * @see #getMaintenances()
   * @generated
   */
  void setMaintenances(Maintenances value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference.
   * @see #setOptions(Config)
   * @see org.uniovi.dsl.scheduling.scheduling.SchedulingPackage#getProgram_Options()
   * @model containment="true"
   * @generated
   */
  Config getOptions();

  /**
   * Sets the value of the '{@link org.uniovi.dsl.scheduling.scheduling.Program#getOptions <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Options</em>' containment reference.
   * @see #getOptions()
   * @generated
   */
  void setOptions(Config value);

} // Program
