/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SchedulingStandaloneSetup extends SchedulingStandaloneSetupGenerated {

	public static void doSetup() {
		new SchedulingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
