/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.tests;

/* @ExtendWith(_InjectionExtension)
@InjectWith(_SchedulingInjectorProvider)
 */public class SchedulingParsingTest {
  /* @Inject
   */private /* ParseHelper<Program> */Object parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field SchedulingParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
