/*
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling;

import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;
import org.uniovi.dsl.scheduling.validation.SchedulingSyntaxErrorMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SchedulingRuntimeModule extends AbstractSchedulingRuntimeModule {
	
	public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
	    return SchedulingSyntaxErrorMessageProvider.class;
	}
}
