/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.uniovi.dsl.scheduling.scheduling.InstallationDef;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Installation Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl#getInstallationName <em>Installation Name</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.InstallationDefImpl#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InstallationDefImpl extends MinimalEObjectImpl.Container implements InstallationDef
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getInstallationName() <em>Installation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstallationName()
   * @generated
   * @ordered
   */
  protected static final String INSTALLATION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInstallationName() <em>Installation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstallationName()
   * @generated
   * @ordered
   */
  protected String installationName = INSTALLATION_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected static final int CAPACITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected int capacity = CAPACITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstallationDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchedulingPackage.Literals.INSTALLATION_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.INSTALLATION_DEF__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInstallationName()
  {
    return installationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstallationName(String newInstallationName)
  {
    String oldInstallationName = installationName;
    installationName = newInstallationName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.INSTALLATION_DEF__INSTALLATION_NAME, oldInstallationName, installationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCapacity()
  {
    return capacity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCapacity(int newCapacity)
  {
    int oldCapacity = capacity;
    capacity = newCapacity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.INSTALLATION_DEF__CAPACITY, oldCapacity, capacity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchedulingPackage.INSTALLATION_DEF__ID:
        return getId();
      case SchedulingPackage.INSTALLATION_DEF__INSTALLATION_NAME:
        return getInstallationName();
      case SchedulingPackage.INSTALLATION_DEF__CAPACITY:
        return getCapacity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchedulingPackage.INSTALLATION_DEF__ID:
        setId((String)newValue);
        return;
      case SchedulingPackage.INSTALLATION_DEF__INSTALLATION_NAME:
        setInstallationName((String)newValue);
        return;
      case SchedulingPackage.INSTALLATION_DEF__CAPACITY:
        setCapacity((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.INSTALLATION_DEF__ID:
        setId(ID_EDEFAULT);
        return;
      case SchedulingPackage.INSTALLATION_DEF__INSTALLATION_NAME:
        setInstallationName(INSTALLATION_NAME_EDEFAULT);
        return;
      case SchedulingPackage.INSTALLATION_DEF__CAPACITY:
        setCapacity(CAPACITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.INSTALLATION_DEF__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case SchedulingPackage.INSTALLATION_DEF__INSTALLATION_NAME:
        return INSTALLATION_NAME_EDEFAULT == null ? installationName != null : !INSTALLATION_NAME_EDEFAULT.equals(installationName);
      case SchedulingPackage.INSTALLATION_DEF__CAPACITY:
        return capacity != CAPACITY_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", installationName: ");
    result.append(installationName);
    result.append(", capacity: ");
    result.append(capacity);
    result.append(')');
    return result.toString();
  }

} //InstallationDefImpl
