/**
 * generated by Xtext 2.31.0
 */
package org.uniovi.dsl.scheduling.scheduling.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.uniovi.dsl.scheduling.scheduling.Config;
import org.uniovi.dsl.scheduling.scheduling.Installations;
import org.uniovi.dsl.scheduling.scheduling.Maintenances;
import org.uniovi.dsl.scheduling.scheduling.Program;
import org.uniovi.dsl.scheduling.scheduling.SchedulingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl#getInstallations <em>Installations</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl#getMaintenances <em>Maintenances</em>}</li>
 *   <li>{@link org.uniovi.dsl.scheduling.scheduling.impl.ProgramImpl#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramImpl extends MinimalEObjectImpl.Container implements Program
{
  /**
   * The cached value of the '{@link #getInstallations() <em>Installations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstallations()
   * @generated
   * @ordered
   */
  protected Installations installations;

  /**
   * The cached value of the '{@link #getMaintenances() <em>Maintenances</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaintenances()
   * @generated
   * @ordered
   */
  protected Maintenances maintenances;

  /**
   * The cached value of the '{@link #getOptions() <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptions()
   * @generated
   * @ordered
   */
  protected Config options;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchedulingPackage.Literals.PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Installations getInstallations()
  {
    return installations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInstallations(Installations newInstallations, NotificationChain msgs)
  {
    Installations oldInstallations = installations;
    installations = newInstallations;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__INSTALLATIONS, oldInstallations, newInstallations);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstallations(Installations newInstallations)
  {
    if (newInstallations != installations)
    {
      NotificationChain msgs = null;
      if (installations != null)
        msgs = ((InternalEObject)installations).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__INSTALLATIONS, null, msgs);
      if (newInstallations != null)
        msgs = ((InternalEObject)newInstallations).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__INSTALLATIONS, null, msgs);
      msgs = basicSetInstallations(newInstallations, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__INSTALLATIONS, newInstallations, newInstallations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Maintenances getMaintenances()
  {
    return maintenances;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMaintenances(Maintenances newMaintenances, NotificationChain msgs)
  {
    Maintenances oldMaintenances = maintenances;
    maintenances = newMaintenances;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__MAINTENANCES, oldMaintenances, newMaintenances);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaintenances(Maintenances newMaintenances)
  {
    if (newMaintenances != maintenances)
    {
      NotificationChain msgs = null;
      if (maintenances != null)
        msgs = ((InternalEObject)maintenances).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__MAINTENANCES, null, msgs);
      if (newMaintenances != null)
        msgs = ((InternalEObject)newMaintenances).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__MAINTENANCES, null, msgs);
      msgs = basicSetMaintenances(newMaintenances, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__MAINTENANCES, newMaintenances, newMaintenances));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Config getOptions()
  {
    return options;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOptions(Config newOptions, NotificationChain msgs)
  {
    Config oldOptions = options;
    options = newOptions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__OPTIONS, oldOptions, newOptions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptions(Config newOptions)
  {
    if (newOptions != options)
    {
      NotificationChain msgs = null;
      if (options != null)
        msgs = ((InternalEObject)options).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__OPTIONS, null, msgs);
      if (newOptions != null)
        msgs = ((InternalEObject)newOptions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SchedulingPackage.PROGRAM__OPTIONS, null, msgs);
      msgs = basicSetOptions(newOptions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchedulingPackage.PROGRAM__OPTIONS, newOptions, newOptions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SchedulingPackage.PROGRAM__INSTALLATIONS:
        return basicSetInstallations(null, msgs);
      case SchedulingPackage.PROGRAM__MAINTENANCES:
        return basicSetMaintenances(null, msgs);
      case SchedulingPackage.PROGRAM__OPTIONS:
        return basicSetOptions(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchedulingPackage.PROGRAM__INSTALLATIONS:
        return getInstallations();
      case SchedulingPackage.PROGRAM__MAINTENANCES:
        return getMaintenances();
      case SchedulingPackage.PROGRAM__OPTIONS:
        return getOptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchedulingPackage.PROGRAM__INSTALLATIONS:
        setInstallations((Installations)newValue);
        return;
      case SchedulingPackage.PROGRAM__MAINTENANCES:
        setMaintenances((Maintenances)newValue);
        return;
      case SchedulingPackage.PROGRAM__OPTIONS:
        setOptions((Config)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.PROGRAM__INSTALLATIONS:
        setInstallations((Installations)null);
        return;
      case SchedulingPackage.PROGRAM__MAINTENANCES:
        setMaintenances((Maintenances)null);
        return;
      case SchedulingPackage.PROGRAM__OPTIONS:
        setOptions((Config)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchedulingPackage.PROGRAM__INSTALLATIONS:
        return installations != null;
      case SchedulingPackage.PROGRAM__MAINTENANCES:
        return maintenances != null;
      case SchedulingPackage.PROGRAM__OPTIONS:
        return options != null;
    }
    return super.eIsSet(featureID);
  }

} //ProgramImpl
